<!-- 
emba - EMBEDDED LINUX ANALYZER

Copyright 2020-2021 Siemens AG
Copyright 2020-2021 Siemens Energy AG

emba comes with ABSOLUTELY NO WARRANTY. This is free software, and you are
welcome to redistribute it under the terms of the GNU General Public License.
See LICENSE file for usage of this software.

emba is licensed under GPLv3

Author(s): Michael Messner, Pascal Eckmann, Stefan Haboeck
-->

<!-- Used icons: https://github.com/CoreyGinnivan/system-uicons -->
 
<!DOCTYPE html>
<html lang="en">
<head>
  <title>EMBA firmware report</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="./../style/style.css" type="text/css">
  <link rel="icon" type="image/png" href="./../style/favicon.png">
</head>
<body>

<div id="sidenav" class="side">
  <div class="logo">
    <a class="inherit" href="./../index.html"><img class="inherit" src="./../style/emba.svg" alt="emba logo"></a>
  </div>
  <div id="nav">
      <a class="back" href="./../index.html">&laquo; Back to main</a>
<a class="modul" href="./../s21_python_check.html" title="./../s21_python_check.html" >&laquo; Back to s21_python_check</a>
      <!-- navigation start -->
      <!-- navigation end -->
      <input id="expand" class="expand_njs hidden" type="button" value="More results:" onclick="this.value=this.value=='+ Show more results'?'- Hide more results':'+ Show more results';">
      <div class="expand_area">
        <!-- etc start -->
        <!-- etc end -->
      </div>
  </div>
  <a href="TIMELINK"><div id="buttonTimeInvisible" class="rectButton"><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" focusable="false" width="40" height="40" style="-ms-transform: rotate(360deg); -webkit-transform: rotate(360deg); transform: rotate(360deg);" preserveAspectRatio="xMidYMid meet" viewBox="0 0 21 21"><g fill="none" fill-rule="evenodd" stroke="white" stroke-linecap="round" stroke-linejoin="round" transform="matrix(-1 0 0 1 19 2)"><circle cx="8.5" cy="8.5" r="8"/><path d="M8.5 5.5v4H5"/></g></svg></div></a>
  <div id="buttonSizer" class="rectButton buttonClose" onclick="buttonNav()"></div>
</div>
<div id="main" class="main">
  <!-- content start -->
<pre>************* Module werkzeug.debug</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/debug/__init__.py:44:4: C0103: Constant name "_machine_id" doesn't conform to UPPER_CASE naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/debug/__init__.py:44:4: W0603: Using the global statement (global-statement)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/debug/__init__.py:55:45: C0103: Variable name "f" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/debug/__init__.py:68:52: C0103: Variable name "f" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/debug/__init__.py:80:12: C0415: Import outside toplevel (subprocess.Popen, subprocess.PIPE) (import-outside-toplevel)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/debug/__init__.py:94:12: C0415: Import outside toplevel (winreg) (import-outside-toplevel)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/debug/__init__.py:104:21: C0103: Variable name "rk" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/debug/__init__.py:129:8: C0103: Attribute name "id" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/debug/__init__.py:122:0: R0903: Too few public methods (0/2) (too-few-public-methods)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/debug/__init__.py:143:4: C0103: Variable name "rv" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/debug/__init__.py:154:12: C0103: Variable name "rv" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/debug/__init__.py:185:4: C0103: Variable name "h" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/debug/__init__.py:207:16: C0103: Variable name "rv" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/debug/__init__.py:213:12: C0103: Variable name "rv" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/debug/__init__.py:132:0: R0912: Too many branches (13/12) (too-many-branches)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/debug/__init__.py:218:0: R0902: Too many instance attributes (14/7) (too-many-instance-attributes)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/debug/__init__.py:248:4: R0913: Too many arguments (9/5) (too-many-arguments)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/debug/__init__.py:313:15: W0703: Catching too general exception Exception (broad-except)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/debug/__init__.py:335:19: W0703: Catching too general exception Exception (broad-except)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/debug/__init__.py:354:14: W0613: Unused argument 'request' (unused-argument)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/debug/__init__.py:353:4: R0201: Method could be a function (no-self-use)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/debug/__init__.py:363:16: C0103: Variable name "ns" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/debug/__init__.py:365:16: C0103: Variable name "ns" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/debug/__init__.py:374:27: W0613: Unused argument 'request' (unused-argument)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/debug/__init__.py:374:4: R0201: Method could be a function (no-self-use)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/debug/__init__.py:397:8: C0103: Variable name "ts" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/debug/__init__.py:443:8: C0103: Variable name "rv" doesn't conform to snake_case naming style (invalid-name)</pre>
<br />
<pre>-----------------------------------</pre>
<pre>Your code has been rated at 8.97/10</pre>
<br />
<pre>irmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:104:0: C0103: Constant name "add_activation_listener" doesn't conform to UPPER_CASE naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:105:0: C0103: Constant name "resources_stream" doesn't conform to UPPER_CASE naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:106:0: C0103: Constant name "cleanup_resources" doesn't conform to UPPER_CASE naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:107:0: C0103: Constant name "resource_dir" doesn't conform to UPPER_CASE naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:108:0: C0103: Constant name "resource_stream" doesn't conform to UPPER_CASE naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:109:0: C0103: Constant name "set_extraction_path" doesn't conform to UPPER_CASE naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:110:0: C0103: Constant name "resource_isdir" doesn't conform to UPPER_CASE naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:111:0: C0103: Constant name "resource_string" doesn't conform to UPPER_CASE naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:112:0: C0103: Constant name "iter_entry_points" doesn't conform to UPPER_CASE naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:113:0: C0103: Constant name "resource_listdir" doesn't conform to UPPER_CASE naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:114:0: C0103: Constant name "resource_filename" doesn't conform to UPPER_CASE naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:115:0: C0103: Constant name "resource_exists" doesn't conform to UPPER_CASE naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:116:0: C0103: Constant name "_distribution_finders" doesn't conform to UPPER_CASE naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:117:0: C0103: Constant name "_namespace_handlers" doesn't conform to UPPER_CASE naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:118:0: C0103: Constant name "_namespace_packages" doesn't conform to UPPER_CASE naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:128:0: C0103: Argument name "v" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:145:4: C0103: Variable name "g" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:146:11: C0103: Variable name "v" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:152:4: C0103: Variable name "g" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:153:11: C0103: Variable name "v" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:162:0: C0103: Argument name "ob" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:162:15: W0613: Unused argument 'key' (unused-argument)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:171:0: C0103: Argument name "ob" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:171:17: W0613: Unused argument 'key' (unused-argument)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:192:4: C0103: Variable name "m" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:355:0: C0103: Argument name "moduleOrReq" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:368:0: W0102: Dangerous default value [] as argument (dangerous-default-value)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:376:36: E1101: Module 'plistlib' has no 'readPlist' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:394:4: W0621: Redefining name 'get_platform' from outer scope (line 415) (redefined-outer-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:394:4: C0415: Import outside toplevel (sysconfig.get_platform) (import-outside-toplevel)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:430:4: C0103: Variable name "reqMac" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:432:8: C0103: Variable name "provMac" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:439:12: C0103: Variable name "provDarwin" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:418:0: R0911: Too many return statements (7/6) (too-many-return-statements)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:464:0: E0102: function already defined line 5 (function-redefined)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:466:4: C0103: Variable name "ns" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:466:9: W0212: Access to a protected member _getframe of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:477:0: E0102: function already defined line 51 (function-redefined)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:504:4: E0213: Method should have "self" as first argument (no-self-argument)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:507:4: E0213: Method should have "self" as first argument (no-self-argument)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:510:4: E0213: Method should have "self" as first argument (no-self-argument)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:516:4: E0213: Method should have "self" as first argument (no-self-argument)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:519:4: E0213: Method should have "self" as first argument (no-self-argument)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:522:4: E0213: Method should have "self" as first argument (no-self-argument)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:529:4: E0213: Method should have "self" as first argument (no-self-argument)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:534:4: E0213: Method should have "self" as first argument (no-self-argument)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:539:4: E0213: Method should have "self" as first argument (no-self-argument)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:544:4: E0213: Method should have "self" as first argument (no-self-argument)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:547:4: E0213: Method should have "self" as first argument (no-self-argument)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:550:4: E0213: Method should have "self" as first argument (no-self-argument)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:575:8: C0103: Variable name "ws" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:577:12: C0415: Import outside toplevel (__main__.__requires__) (import-outside-toplevel)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:597:8: C0103: Variable name "ws" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:663:8: C0103: Variable name "ns" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:663:13: W0212: Access to a protected member _getframe of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:716:4: R0913: Too many arguments (6/5) (too-many-arguments)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:716:4: R0914: Too many local variables (18/15) (too-many-locals)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:771:20: C0103: Variable name "ws" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:780:28: C0103: Variable name "ws" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:870:16: C0103: Variable name "v" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:873:20: R1724: Unnecessary "else" after "continue" (no-else-continue)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:964:36: W0621: Redefining name 'platform' from outer scope (line 33) (redefined-outer-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:1041:23: W0621: Redefining name 'working_set' from outer scope (line 103) (redefined-outer-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:1068:4: R1710: Either all return statements in a function should return an expression, or none of them should. (inconsistent-return-statements)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:1068:4: R0201: Method could be a function (no-self-use)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:1082:19: C0201: Consider iterating the dictionary directly instead of calling .keys() (consider-iterating-dictionary)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:1190:8: W0201: Attribute 'manager' defined outside __init__ (attribute-defined-outside-init)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:1191:8: W0201: Attribute 'cache_path' defined outside __init__ (attribute-defined-outside-init)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:1192:8: W0201: Attribute 'original_error' defined outside __init__ (attribute-defined-outside-init)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:1133:4: R0201: Method could be a function (no-self-use)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:1137:4: R0201: Method could be a function (no-self-use)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:1161:4: R0201: Method could be a function (no-self-use)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:1212:15: W0703: Catching too general exception Exception (broad-except)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:1246:36: W0613: Unused argument 'filename' (unused-argument)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:1246:4: R0201: Method could be a function (no-self-use)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:1362:4: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:1380:4: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:1381:8: W0707: Consider explicitly re-raising using the 'from' keyword (raise-missing-from)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:1369:26: W0613: Unused argument 'extra' (unused-argument)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:1395:36: W0613: Unused argument 'manager' (unused-argument)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:1401:34: W0613: Unused argument 'manager' (unused-argument)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:1463:12: W0122: Use of exec (exec-used)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:1465:12: C0415: Import outside toplevel (linecache.cache) (import-outside-toplevel)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:1470:12: W0122: Use of exec (exec-used)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:1579:0: W0223: Method '_has' is abstract in class 'NullProvider' but is not overridden (abstract-method)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:1579:0: W0223: Method '_isdir' is abstract in class 'NullProvider' but is not overridden (abstract-method)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:1579:0: W0223: Method '_listdir' is abstract in class 'NullProvider' but is not overridden (abstract-method)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:1598:18: W0612: Unused variable 'base' (unused-variable)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:1628:0: W0212: Access to a protected member _register of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:1644:4: W0231: __init__ method from base class 'NullProvider' is not called (super-init-not-called)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:1794:20: R1705: Unnecessary "elif" after "return" (no-else-return)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:1766:19: W0612: Unused variable 'size' (unused-variable)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:1818:8: W0621: Redefining name 'stat' from outer scope (line 29) (redefined-outer-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:1823:38: C0103: Variable name "f" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:1845:20: R1723: Unnecessary "else" after "break" (no-else-break)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:1853:4: W0221: Parameters differ from overridden '_has' method (arguments-differ)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:1857:4: W0221: Parameters differ from overridden '_isdir' method (arguments-differ)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:1860:4: W0221: Parameters differ from overridden '_listdir' method (arguments-differ)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:1850:12: W0201: Attribute '_dirindex' defined outside __init__ (attribute-defined-outside-init)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:1870:21: E1101: Module 'zipimport' has no 'zipimporter' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:1885:4: W0231: __init__ method from base class 'EmptyProvider' is not called (super-init-not-called)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:1898:71: C0103: Variable name "f" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:1903:4: R0201: Method could be a function (no-self-use)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:1935:4: W0231: __init__ method from base class 'DefaultProvider' is not called (super-init-not-called)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:1943:4: W0231: __init__ method from base class 'ZipProvider' is not called (super-init-not-called)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:1965:4: E1137: '_distribution_finders' does not support item assignment (unsupported-assignment-operation)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:1992:37: E1101: Module 'zipimport' has no 'zipimporter' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:1997:34: E1101: Module 'zipimport' has no 'zipimporter' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:2002:16: E1101: Module 'zipimport' has no 'zipimporter' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:2005:17: W0613: Unused argument 'importer' (unused-argument)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:2005:27: W0613: Unused argument 'path_item' (unused-argument)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:2005:38: W0613: Unused argument 'only' (unused-argument)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:2038:17: W0613: Unused argument 'importer' (unused-argument)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:2070:17: W0613: Unused argument 'path_item' (unused-argument)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:2112:4: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:2144:23: C0103: Variable name "f" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:2189:4: E1137: '_namespace_handlers' does not support item assignment (unsupported-assignment-operation)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:2192:0: C0103: Argument name "packageName" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:2257:0: C0103: Argument name "packageName" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:2275:16: W0707: Consider explicitly re-raising using the 'from' keyword (raise-missing-from)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:2303:0: C0103: Argument name "packageName" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:2303:20: W0613: Unused argument 'importer' (unused-argument)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:2317:27: E1101: Module 'zipimport' has no 'zipimporter' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:2323:0: C0103: Argument name "packageName" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:2323:20: W0613: Unused argument 'importer' (unused-argument)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:2323:30: W0613: Unused argument 'path_item' (unused-argument)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:2323:41: W0613: Unused argument 'packageName' (unused-argument)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:2323:54: W0613: Unused argument 'module' (unused-argument)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:2347:0: W0102: Dangerous default value {} as argument (dangerous-default-value)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:2372:0: C0103: Argument name "packageName" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:2383:12: C0103: Variable name "s" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:2384:12: C0103: Variable name "s" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:2389:12: C0103: Variable name "ss" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:2390:16: C0103: Variable name "s" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:2412:4: R0913: Too many arguments (6/5) (too-many-arguments)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:2422:8: C0103: Variable name "s" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:2424:12: C0103: Variable name "s" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:2426:12: C0103: Variable name "s" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:2432:19: W0621: Redefining name 'require' from outer scope (line 2) (redefined-outer-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:2432:4: W1113: Keyword argument before variable positional arguments list in the definition of load function (keyword-arg-before-vararg)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:2455:12: W0707: Consider explicitly re-raising using the 'from' keyword (raise-missing-from)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:2490:8: C0103: Variable name "m" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:2515:12: C0103: Variable name "ep" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:2563:0: R0902: Too many instance attributes (11/7) (too-many-instance-attributes)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:2569:47: W0621: Redefining name 'platform' from outer scope (line 33) (redefined-outer-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:2567:4: R0913: Too many arguments (8/5) (too-many-arguments)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:2582:43: W0621: Redefining name 'platform' from outer scope (line 33) (redefined-outer-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:2585:12: W0642: Invalid assignment to cls in method (self-cls-assignment)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:2592:15: W0212: Access to a protected member _reload_version of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:2655:8: C0103: Variable name "LV" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:2691:16: W0707: Consider explicitly re-raising using the 'from' keyword (raise-missing-from)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:2708:4: C0103: Argument name "dm" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:2730:8: C0103: Variable name "dm" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:2738:8: C0103: Variable name "dm" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:2745:16: W0707: Consider explicitly re-raising using the 'from' keyword (raise-missing-from)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:2762:15: W0703: Catching too general exception Exception (broad-except)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:2758:19: W0212: Access to a protected member _get_metadata_path of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:2801:8: R1705: Unnecessary "else" after "return" (no-else-return)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:2822:16: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:2851:8: C0103: Variable name "ep" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:2900:12: C0103: Variable name "p" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:2902:16: R1723: Unnecessary "else" after "break" (no-else-break)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:2930:16: C0103: Variable name "np" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:2930:39: W0631: Using possibly undefined loop variable 'p' (undefined-loop-variable)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:2936:16: C0103: Variable name "p" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:2872:4: R0912: Too many branches (15/12) (too-many-branches)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:2953:12: C0103: Variable name "fn" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:2644:12: W0201: Attribute '_key' defined outside __init__ (attribute-defined-outside-init)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:2650:12: W0201: Attribute '_parsed_version' defined outside __init__ (attribute-defined-outside-init)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:2704:12: W0201: Attribute '__dep_map' defined outside __init__ (attribute-defined-outside-init)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:2861:21: W0201: Attribute '_ep_map' defined outside __init__ (attribute-defined-outside-init)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:3030:8: C0103: Variable name "dm" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:3017:12: W0201: Attribute '_pkg_info' defined outside __init__ (attribute-defined-outside-init)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:3025:12: W0201: Attribute '__dep_map' defined outside __init__ (attribute-defined-outside-init)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:3030:13: W0201: Attribute '__dep_map' defined outside __init__ (attribute-defined-outside-init)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:3061:4: C0103: Variable name "g" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:3065:14: W0212: Access to a protected member _getframe of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:3112:8: C0103: Attribute name "hashCmp" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:3103:12: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:3104:8: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:3105:12: W0707: Consider explicitly re-raising using the 'from' keyword (raise-missing-from)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:3149:4: C0103: Argument name "s" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:3164:0: C0103: Argument name "ob" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:3166:4: W0621: Redefining name 'types' from outer scope (line 25) (redefined-outer-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:3167:8: C0103: Variable name "t" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:3164:0: R1710: Either all return statements in a function should return an expression, or none of them should. (inconsistent-return-statements)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:3191:0: C0103: Argument name "s" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:3236:0: C0103: Argument name "f" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:3242:0: C0103: Argument name "g" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:3266:4: W0621: Redefining name 'working_set' from outer scope (line 103) (redefined-outer-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:3269:4: W0621: Redefining name 'require' from outer scope (line 2) (redefined-outer-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:3270:4: W0621: Redefining name 'iter_entry_points' from outer scope (line 8) (redefined-outer-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:3271:4: W0621: Redefining name 'add_activation_listener' from outer scope (line 104) (redefined-outer-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:3272:4: W0621: Redefining name 'run_script' from outer scope (line 5) (redefined-outer-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:3274:4: W0621: Redefining name 'run_main' from outer scope (line 474) (redefined-outer-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:3266:18: W0212: Access to a protected member _build_master of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:3269:4: W0641: Possibly unused variable 'require' (possibly-unused-variable)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:3270:4: W0641: Possibly unused variable 'iter_entry_points' (possibly-unused-variable)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:3274:4: W0641: Possibly unused variable 'run_main' (possibly-unused-variable)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:61:0: C0411: standard import "from os import utime" should be placed before "from pkg_resources.extern import six" (wrong-import-order)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:69:0: C0411: standard import "from os import open as os_open" should be placed before "from pkg_resources.extern import six" (wrong-import-order)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:70:0: C0411: standard import "from os.path import isdir, split" should be placed before "from pkg_resources.extern import six" (wrong-import-order)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:80:0: C0411: third party import "from pkg_resources.extern import appdirs" should be placed before "from . import py31compat" (wrong-import-order)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:81:0: C0411: third party import "from pkg_resources.extern import packaging" should be placed before "from . import py31compat" (wrong-import-order)</pre>
<br />
<pre>-----------------------------------</pre>
<pre>Your code has been rated at 7.85/10</pre>
<br />
<pre>/__init__.py:1130:12: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1130:46: E1101: Instance of 'Misc' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1135:12: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1135:47: E1101: Instance of 'Misc' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1139:15: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1140:12: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1140:46: E1101: Instance of 'Misc' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1144:15: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1145:12: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1145:47: E1101: Instance of 'Misc' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1149:15: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1150:12: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1150:46: E1101: Instance of 'Misc' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1156:12: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1156:41: E1101: Instance of 'Misc' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1161:15: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1162:12: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1162:43: E1101: Instance of 'Misc' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1167:15: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1168:12: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1168:43: E1101: Instance of 'Misc' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1172:15: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1172:47: E1101: Instance of 'Misc' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1177:15: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1178:12: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1178:49: E1101: Instance of 'Misc' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1183:15: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1184:12: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1184:49: E1101: Instance of 'Misc' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1189:15: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1190:12: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1190:50: E1101: Instance of 'Misc' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1195:15: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1196:12: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1196:52: E1101: Instance of 'Misc' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1201:15: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1202:12: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1202:51: E1101: Instance of 'Misc' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1208:15: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1208:53: E1101: Instance of 'Misc' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1213:15: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1214:12: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1214:49: E1101: Instance of 'Misc' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1219:15: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1219:47: E1101: Instance of 'Misc' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1223:34: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1224:33: E1101: Instance of 'Misc' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1228:15: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1229:12: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1229:46: E1101: Instance of 'Misc' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1235:15: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1235:47: E1101: Instance of 'Misc' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1239:15: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1239:49: E1101: Instance of 'Misc' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1247:15: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1247:57: E1101: Instance of 'Misc' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1249:16: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1249:46: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1252:4: C0103: Argument name "t" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1256:4: C0103: Argument name "x" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1256:4: R0201: Method could be a function (no-self-use)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1264:15: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1265:12: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1265:49: E1101: Instance of 'Misc' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1271:15: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1272:12: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1272:48: E1101: Instance of 'Misc' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1277:15: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1278:12: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1278:44: E1101: Instance of 'Misc' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1283:15: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1284:12: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1284:44: E1101: Instance of 'Misc' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1288:15: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1289:12: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1289:43: E1101: Instance of 'Misc' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1294:15: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1295:12: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1295:39: E1101: Instance of 'Misc' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1300:15: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1301:12: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1301:39: E1101: Instance of 'Misc' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1305:8: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1311:8: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1313:4: C0103: Argument name "tagList" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1320:8: R1705: Unnecessary "else" after "return" (no-else-return)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1321:19: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1322:16: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1322:41: E1101: Instance of 'Misc' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1324:12: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1324:37: E1101: Instance of 'Misc' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1313:4: R1710: Either all return statements in a function should return an expression, or none of them should. (inconsistent-return-statements)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1326:4: R0913: Too many arguments (6/5) (too-many-arguments)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1329:12: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1337:12: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1340:19: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1342:19: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1342:37: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1326:4: R1710: Either all return statements in a function should return an expression, or none of them should. (inconsistent-return-statements)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1383:35: E1101: Instance of 'Misc' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1388:8: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1388:29: E1101: Instance of 'Misc' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1401:8: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1403:4: C0103: Argument name "className" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1413:4: C0103: Argument name "className" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1416:8: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1418:4: C0103: Argument name "n" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1420:8: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1424:8: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1429:29: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1429:45: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1426:4: R1710: Either all return statements in a function should return an expression, or none of them should. (inconsistent-return-statements)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1434:29: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1434:48: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1431:4: R1710: Either all return statements in a function should return an expression, or none of them should. (inconsistent-return-statements)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1439:19: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1436:4: R1710: Either all return statements in a function should return an expression, or none of them should. (inconsistent-return-statements)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1446:34: E1101: Instance of 'Misc' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1453:19: W0212: Access to a protected member _windowingsystem_cached of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1455:12: C0103: Variable name "ws" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1456:24: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1459:4: C0103: Argument name "kw" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1466:15: C0103: Variable name "v" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1468:33: C0321: More than one statement on a single line (multiple-statements)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1470:20: C0103: Variable name "v" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1472:20: C0103: Variable name "nv" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1481:24: C0103: Variable name "v" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1489:8: C0103: Variable name "w" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1492:12: C0103: Variable name "w" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1492:16: W0212: Access to a protected member _root of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1495:12: C0103: Variable name "n" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1498:12: C0103: Variable name "w" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1509:8: C0103: Variable name "f" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1519:8: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1530:8: C0103: Variable name "w" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1531:24: C0321: More than one statement on a single line (multiple-statements)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1531:24: C0103: Variable name "w" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1531:28: E1101: Instance of 'Misc' has no 'master' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1541:8: W0621: Redefining name 'getboolean' from outer scope (line 601) (redefined-outer-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1543:8: W0621: Redefining name 'getint' from outer scope (line 596) (redefined-outer-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1551:45: W0621: Redefining name 'E' from outer scope (line 38) (redefined-outer-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1551:51: W0621: Redefining name 'N' from outer scope (line 38) (redefined-outer-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1551:54: W0621: Redefining name 'W' from outer scope (line 38) (redefined-outer-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1551:60: W0621: Redefining name 'X' from outer scope (line 38) (redefined-outer-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1551:63: W0621: Redefining name 'Y' from outer scope (line 38) (redefined-outer-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1538:4: R0914: Too many local variables (25/15) (too-many-locals)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1540:49: C0321: More than one statement on a single line (multiple-statements)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1541:21: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1543:17: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1544:8: C0103: Argument name "s" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1551:15: C0103: Variable name "b" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1551:18: C0103: Variable name "f" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1551:21: C0103: Variable name "h" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1551:27: C0103: Variable name "s" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1551:30: C0103: Variable name "t" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1551:33: C0103: Variable name "w" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1551:36: C0103: Variable name "x" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1551:39: C0103: Variable name "y" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1551:42: C0103: Variable name "A" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1551:45: C0103: Variable name "E" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1551:48: C0103: Variable name "K" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1551:51: C0103: Variable name "N" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1551:54: C0103: Variable name "W" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1551:57: C0103: Variable name "T" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1551:60: C0103: Variable name "X" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1551:63: C0103: Variable name "Y" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1551:66: C0103: Variable name "D" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1553:8: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1569:13: C0321: More than one statement on a single line (multiple-statements)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1570:25: C0321: More than one statement on a single line (multiple-statements)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1579:13: C0321: More than one statement on a single line (multiple-statements)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1580:25: C0321: More than one statement on a single line (multiple-statements)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1601:18: C0103: Variable name "tb" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1608:12: C0103: Variable name "x" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1608:17: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1608:35: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1609:12: C0103: Variable name "x" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1609:16: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1614:8: C0103: Variable name "x" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1614:12: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1614:30: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1617:4: C0103: Argument name "kw" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1624:48: E1101: Instance of 'Misc' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1626:49: E1101: Instance of 'Misc' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1627:8: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1627:31: E1101: Instance of 'Misc' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1617:4: R1710: Either all return statements in a function should return an expression, or none of them should. (inconsistent-return-statements)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1643:15: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1643:28: E1101: Instance of 'Misc' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1652:20: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1654:26: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1654:39: E1101: Instance of 'Misc' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1658:15: E1101: Instance of 'Misc' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1662:68: E1101: Instance of 'Misc' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1667:4: W0102: Dangerous default value _noarg_ (builtins.list) as argument (dangerous-default-value)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1674:8: R1705: Unnecessary "else" after "return" (no-else-return)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1675:36: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1676:37: E1101: Instance of 'Misc' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1678:12: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1678:46: E1101: Instance of 'Misc' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1667:4: R1710: Either all return statements in a function should return an expression, or none of them should. (inconsistent-return-statements)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1686:16: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1687:19: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1687:50: E1101: Instance of 'Misc' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1696:16: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1697:19: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1698:42: E1101: Instance of 'Misc' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1707:8: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1707:39: E1101: Instance of 'Misc' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1723:32: E1101: Instance of 'Misc' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1728:29: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1736:16: R1705: Unnecessary "elif" after "return" (no-else-return)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1739:27: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1741:27: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1746:4: C0103: Argument name "kw" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1758:16: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1759:16: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1759:46: E1101: Instance of 'Misc' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1761:14: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1762:36: E1101: Instance of 'Misc' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1746:4: R1710: Either all return statements in a function should return an expression, or none of them should. (inconsistent-return-statements)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1767:4: W0102: Dangerous default value {} as argument (dangerous-default-value)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1777:4: C0103: Argument name "x" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1777:4: C0103: Argument name "y" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1782:12: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1783:36: E1101: Instance of 'Misc' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1785:4: W0102: Dangerous default value _noarg_ (builtins.list) as argument (dangerous-default-value)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1792:8: R1705: Unnecessary "else" after "return" (no-else-return)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1793:36: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1794:37: E1101: Instance of 'Misc' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1796:12: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1796:46: E1101: Instance of 'Misc' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1785:4: R1710: Either all return statements in a function should return an expression, or none of them should. (inconsistent-return-statements)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1798:4: W0102: Dangerous default value {} as argument (dangerous-default-value)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1811:12: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1811:41: E1101: Instance of 'Misc' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1824:16: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1824:34: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1825:38: E1101: Instance of 'Misc' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1835:8: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1840:8: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1846:37: E1101: Instance of 'Misc' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1847:15: C0103: Variable name "v" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1849:8: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1854:15: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1855:12: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1861:15: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1861:33: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1865:15: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1865:33: E1101: Instance of 'Misc' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1455:17: W0201: Attribute '_windowingsystem_cached' defined outside __init__ (attribute-defined-outside-init)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:611:0: R0904: Too many public methods (126/20) (too-many-public-methods)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1886:8: W0702: No exception type(s) specified (bare-except)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1878:4: R1710: Either all return statements in a function should return an expression, or none of them should. (inconsistent-return-statements)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1868:0: R0903: Too few public methods (1/2) (too-few-public-methods)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1896:14: E1101: Instance of 'XView' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1896:27: E1101: Instance of 'XView' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1898:19: E1101: Instance of 'XView' has no '_getdoubles' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1894:4: R1710: Either all return statements in a function should return an expression, or none of them should. (inconsistent-return-statements)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1903:8: E1101: Instance of 'XView' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1903:21: E1101: Instance of 'XView' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1908:8: E1101: Instance of 'XView' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1908:21: E1101: Instance of 'XView' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1917:14: E1101: Instance of 'YView' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1917:27: E1101: Instance of 'YView' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1919:19: E1101: Instance of 'YView' has no '_getdoubles' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1915:4: R1710: Either all return statements in a function should return an expression, or none of them should. (inconsistent-return-statements)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1924:8: E1101: Instance of 'YView' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1924:21: E1101: Instance of 'YView' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1929:8: E1101: Instance of 'YView' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1929:21: E1101: Instance of 'YView' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1935:4: C0103: Argument name "minNumer" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1935:4: C0103: Argument name "minDenom" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1935:4: C0103: Argument name "maxNumer" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1935:4: C0103: Argument name "maxDenom" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1941:15: E1101: Instance of 'Wm' has no '_getints' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1942:12: E1101: Instance of 'Wm' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1942:41: E1101: Instance of 'Wm' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1966:36: E1101: Instance of 'Wm' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1967:15: E1101: Instance of 'Wm' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1974:15: E1101: Instance of 'Wm' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1974:44: E1101: Instance of 'Wm' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1984:41: E1101: Instance of 'Wm' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1986:12: E1101: Instance of 'Wm' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1988:20: E1101: Instance of 'Wm' has no '_nametowidget' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1989:29: E1101: Instance of 'Wm' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1989:47: E1101: Instance of 'Wm' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1978:4: R1710: Either all return statements in a function should return an expression, or none of them should. (inconsistent-return-statements)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1997:15: E1101: Instance of 'Wm' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1997:45: E1101: Instance of 'Wm' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2004:15: E1101: Instance of 'Wm' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2004:47: E1101: Instance of 'Wm' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2012:15: E1101: Instance of 'Wm' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2012:48: E1101: Instance of 'Wm' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2022:8: E1101: Instance of 'Wm' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2028:15: E1101: Instance of 'Wm' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2028:43: E1101: Instance of 'Wm' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2032:4: C0103: Argument name "newGeometry" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2035:15: E1101: Instance of 'Wm' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2035:46: E1101: Instance of 'Wm' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2039:4: C0103: Argument name "baseWidth" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2039:4: C0103: Argument name "baseHeight" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2039:4: C0103: Argument name "widthInc" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2039:4: C0103: Argument name "heightInc" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2046:15: E1101: Instance of 'Wm' has no '_getints' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2046:29: E1101: Instance of 'Wm' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2047:26: E1101: Instance of 'Wm' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2052:4: C0103: Argument name "pathName" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2055:15: E1101: Instance of 'Wm' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2055:43: E1101: Instance of 'Wm' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2068:8: R1705: Unnecessary "else" after "return" (no-else-return)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2069:19: E1101: Instance of 'Wm' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2069:52: E1101: Instance of 'Wm' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2071:19: E1101: Instance of 'Wm' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2071:52: E1101: Instance of 'Wm' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2077:15: E1101: Instance of 'Wm' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2077:45: E1101: Instance of 'Wm' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2084:15: E1101: Instance of 'Wm' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2084:46: E1101: Instance of 'Wm' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2088:4: C0103: Argument name "newName" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2091:15: E1101: Instance of 'Wm' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2091:46: E1101: Instance of 'Wm' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2095:4: W1113: Keyword argument before variable positional arguments list in the definition of wm_iconphoto function (keyword-arg-before-vararg)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2116:12: E1101: Instance of 'Wm' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2116:44: E1101: Instance of 'Wm' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2118:12: E1101: Instance of 'Wm' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2118:44: E1101: Instance of 'Wm' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2122:4: C0103: Argument name "x" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2122:4: C0103: Argument name "y" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2125:15: E1101: Instance of 'Wm' has no '_getints' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2125:29: E1101: Instance of 'Wm' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2126:34: E1101: Instance of 'Wm' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2130:4: C0103: Argument name "pathName" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2133:15: E1101: Instance of 'Wm' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2133:48: E1101: Instance of 'Wm' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2141:8: E1101: Instance of 'Wm' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2149:15: E1101: Instance of 'Wm' has no '_getints' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2149:29: E1101: Instance of 'Wm' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2150:29: E1101: Instance of 'Wm' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2158:15: E1101: Instance of 'Wm' has no '_getints' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2158:29: E1101: Instance of 'Wm' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2159:29: E1101: Instance of 'Wm' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2167:15: E1101: Instance of 'Wm' has no '_getboolean' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2167:32: E1101: Instance of 'Wm' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2168:38: E1101: Instance of 'Wm' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2176:15: E1101: Instance of 'Wm' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2176:50: E1101: Instance of 'Wm' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2185:22: E1101: Instance of 'Wm' has no '_register' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2188:15: E1101: Instance of 'Wm' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2189:30: E1101: Instance of 'Wm' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2196:15: E1101: Instance of 'Wm' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2196:47: E1101: Instance of 'Wm' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2204:15: E1101: Instance of 'Wm' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2204:46: E1101: Instance of 'Wm' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2211:15: E1101: Instance of 'Wm' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2211:43: E1101: Instance of 'Wm' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2217:15: E1101: Instance of 'Wm' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2217:43: E1101: Instance of 'Wm' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2224:15: E1101: Instance of 'Wm' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2224:47: E1101: Instance of 'Wm' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2231:15: E1101: Instance of 'Wm' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2231:46: E1101: Instance of 'Wm' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:1932:0: R0904: Too many public methods (31/20) (too-many-public-methods)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2253:8: C0103: Attribute name "tk" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2241:4: R0913: Too many arguments (7/5) (too-many-arguments)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2255:12: C0415: Import outside toplevel (os) (import-outside-toplevel)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2275:8: C0103: Constant name "_default_root" doesn't conform to UPPER_CASE naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2275:8: W0603: Using the global statement (global-statement)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2302:12: C0103: Variable name "c" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2302:47: C0321: More than one statement on a single line (multiple-statements)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2305:8: C0103: Constant name "_default_root" doesn't conform to UPPER_CASE naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2305:8: W0603: Using the global statement (global-statement)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2309:4: C0103: Argument name "baseName" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2309:4: C0103: Argument name "className" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2320:8: W0622: Redefining built-in 'dir' (redefined-builtin)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2313:8: C0415: Import outside toplevel (os) (import-outside-toplevel)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2314:33: C0321: More than one statement on a single line (multiple-statements)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2321:8: W0122: Use of exec (exec-used)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2325:12: W0122: Use of exec (exec-used)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2329:12: W0122: Use of exec (exec-used)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2331:4: C0103: Argument name "tb" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2336:8: C0415: Import outside toplevel (traceback) (import-outside-toplevel)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2331:4: R0201: Method could be a function (no-self-use)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:4561:4: W0201: Attribute 'test' defined outside __init__ (attribute-defined-outside-init)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2362:0: C0103: Function name "Tcl" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2362:0: C0103: Argument name "screenName" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2362:0: C0103: Argument name "baseName" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2362:0: C0103: Argument name "className" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2362:0: C0103: Argument name "useTk" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2371:4: W0102: Dangerous default value {} as argument (dangerous-default-value)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2387:8: E1101: Instance of 'Pack' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2388:36: E1101: Instance of 'Pack' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2389:16: E1101: Instance of 'Pack' has no '_options' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2395:8: E1101: Instance of 'Pack' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2395:39: E1101: Instance of 'Pack' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2402:8: C0103: Variable name "d" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2402:23: E1101: Instance of 'Pack' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2402:32: E1101: Instance of 'Pack' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2402:61: E1101: Instance of 'Pack' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2404:22: E1101: Instance of 'Pack' has no 'nametowidget' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2417:4: W0102: Dangerous default value {} as argument (dangerous-default-value)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2439:8: E1101: Instance of 'Place' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2440:37: E1101: Instance of 'Place' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2441:16: E1101: Instance of 'Place' has no '_options' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2447:8: E1101: Instance of 'Place' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2447:40: E1101: Instance of 'Place' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2454:8: C0103: Variable name "d" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2454:23: E1101: Instance of 'Place' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2454:32: E1101: Instance of 'Place' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2454:62: E1101: Instance of 'Place' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2456:22: E1101: Instance of 'Place' has no 'nametowidget' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2469:4: W0102: Dangerous default value {} as argument (dangerous-default-value)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2484:8: E1101: Instance of 'Grid' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2485:36: E1101: Instance of 'Grid' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2486:16: E1101: Instance of 'Grid' has no '_options' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2494:8: E1101: Instance of 'Grid' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2494:39: E1101: Instance of 'Grid' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2500:8: E1101: Instance of 'Grid' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2500:39: E1101: Instance of 'Grid' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2505:8: C0103: Variable name "d" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2505:23: E1101: Instance of 'Grid' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2505:32: E1101: Instance of 'Grid' has no 'tk' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2505:61: E1101: Instance of 'Grid' has no '_w' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2507:22: E1101: Instance of 'Grid' has no 'nametowidget' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2530:8: C0103: Attribute name "tk" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2560:8: C0103: Attribute name "widgetName" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2524:12: C0103: Constant name "_default_root" doesn't conform to UPPER_CASE naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2524:12: W0603: Using the global statement (global-statement)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2537:15: W0212: Access to a protected member _last_child_ids of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2538:16: W0212: Access to a protected member _last_child_ids of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2539:20: W0212: Access to a protected member _last_child_ids of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2540:12: W0212: Access to a protected member _last_child_ids of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2546:11: W0212: Access to a protected member _w of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2549:22: W0212: Access to a protected member _w of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2555:4: W0102: Dangerous default value {} as argument (dangerous-default-value)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2555:4: W0102: Dangerous default value {} as argument (dangerous-default-value)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2555:4: R0913: Too many arguments (6/5) (too-many-arguments)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2565:15: C0103: Variable name "v" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2569:15: C0103: Variable name "v" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2574:12: C0103: Variable name "c" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2574:47: C0321: More than one statement on a single line (multiple-statements)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2529:8: W0201: Attribute 'master' defined outside __init__ (attribute-defined-outside-init)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2530:8: W0201: Attribute 'tk' defined outside __init__ (attribute-defined-outside-init)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2545:8: W0201: Attribute '_name' defined outside __init__ (attribute-defined-outside-init)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2547:12: W0201: Attribute '_w' defined outside __init__ (attribute-defined-outside-init)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2549:12: W0201: Attribute '_w' defined outside __init__ (attribute-defined-outside-init)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2550:8: W0201: Attribute 'children' defined outside __init__ (attribute-defined-outside-init)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2590:4: W0107: Unnecessary pass statement (unnecessary-pass)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2596:4: W0102: Dangerous default value {} as argument (dangerous-default-value)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2612:37: C0321: More than one statement on a single line (multiple-statements)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2626:4: W0102: Dangerous default value {} as argument (dangerous-default-value)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2670:0: R0901: Too many ancestors (9/7) (too-many-ancestors)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2673:4: W0102: Dangerous default value {} as argument (dangerous-default-value)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2689:4: C0103: Argument name "tagOrId" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2697:4: C0103: Argument name "tagOrId" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2701:4: C0103: Argument name "x" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2701:4: C0103: Argument name "y" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2701:4: R0913: Too many arguments (6/5) (too-many-arguments)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2708:4: C0103: Argument name "x1" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2708:4: C0103: Argument name "y1" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2708:4: C0103: Argument name "x2" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2708:4: C0103: Argument name "y2" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2708:4: R0913: Too many arguments (6/5) (too-many-arguments)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2713:4: C0103: Argument name "x1" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2713:4: C0103: Argument name "y1" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2713:4: C0103: Argument name "x2" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2713:4: C0103: Argument name "y2" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2713:4: R0913: Too many arguments (6/5) (too-many-arguments)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2718:4: C0103: Argument name "tagOrId" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2728:4: C0103: Argument name "tagOrId" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2735:4: C0103: Argument name "tagOrId" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2763:4: C0103: Argument name "itemType" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2763:4: C0103: Argument name "kw" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2830:4: C0103: Argument name "tagOrId" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2838:4: C0103: Argument name "tagOrId" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2842:4: C0103: Argument name "x" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2842:4: C0103: Argument name "y" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2849:4: C0103: Argument name "x1" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2849:4: C0103: Argument name "y1" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2849:4: C0103: Argument name "x2" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2849:4: C0103: Argument name "y2" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2854:4: C0103: Argument name "x1" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2854:4: C0103: Argument name "y1" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2854:4: C0103: Argument name "x2" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2854:4: C0103: Argument name "y2" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2859:4: C0103: Argument name "tagOrId" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2886:4: C0103: Argument name "tagOrId" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2891:4: C0103: Argument name "tagOrId" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2917:4: C0103: Argument name "tagOrId" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2917:4: C0103: Argument name "x" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2917:4: C0103: Argument name "y" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2926:4: W0102: Dangerous default value {} as argument (dangerous-default-value)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2945:4: C0103: Argument name "x" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2945:4: C0103: Argument name "y" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2949:4: C0103: Argument name "x" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2949:4: C0103: Argument name "y" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2955:4: C0103: Argument name "tagOrId" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2963:4: C0103: Argument name "tagOrId" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2971:4: C0103: Argument name "tagOrId" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2975:4: C0103: Argument name "tagOrId" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2670:0: R0904: Too many public methods (55/20) (too-many-public-methods)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:2983:4: W0102: Dangerous default value {} as argument (dangerous-default-value)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3016:0: R0901: Too many ancestors (8/7) (too-many-ancestors)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3019:4: W0102: Dangerous default value {} as argument (dangerous-default-value)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3053:4: C0103: Argument name "x" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3057:4: C0103: Argument name "x" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3069:4: W0221: Parameters differ from overridden 'selection_clear' method (arguments-differ)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3105:4: W0102: Dangerous default value {} as argument (dangerous-default-value)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3125:4: W0102: Dangerous default value {} as argument (dangerous-default-value)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3146:0: R0901: Too many ancestors (9/7) (too-many-ancestors)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3149:4: W0102: Dangerous default value {} as argument (dangerous-default-value)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3178:8: R1705: Unnecessary "else" after "return" (no-else-return)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3187:24: C0321: More than one statement on a single line (multiple-statements)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3194:4: C0103: Argument name "y" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3199:4: C0103: Argument name "x" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3199:4: C0103: Argument name "y" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3203:4: C0103: Argument name "x" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3203:4: C0103: Argument name "y" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3219:4: W0221: Parameters differ from overridden 'selection_clear' method (arguments-differ)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3265:4: W0102: Dangerous default value {} as argument (dangerous-default-value)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3274:4: C0103: Argument name "x" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3274:4: C0103: Argument name "y" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3282:4: W0102: Dangerous default value {} as argument (dangerous-default-value)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3282:4: C0103: Argument name "itemType" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3287:4: W0102: Dangerous default value {} as argument (dangerous-default-value)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3291:4: W0102: Dangerous default value {} as argument (dangerous-default-value)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3295:4: W0102: Dangerous default value {} as argument (dangerous-default-value)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3299:4: W0102: Dangerous default value {} as argument (dangerous-default-value)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3303:4: W0102: Dangerous default value {} as argument (dangerous-default-value)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3307:4: W0102: Dangerous default value {} as argument (dangerous-default-value)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3307:4: C0103: Argument name "itemType" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3312:4: W0102: Dangerous default value {} as argument (dangerous-default-value)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3316:4: W0102: Dangerous default value {} as argument (dangerous-default-value)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3320:4: W0102: Dangerous default value {} as argument (dangerous-default-value)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3324:4: W0102: Dangerous default value {} as argument (dangerous-default-value)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3328:4: W0102: Dangerous default value {} as argument (dangerous-default-value)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3343:16: C0103: Variable name "c" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3361:24: C0321: More than one statement on a single line (multiple-statements)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3369:4: C0103: Argument name "x" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3369:4: C0103: Argument name "y" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3262:0: R0904: Too many public methods (24/20) (too-many-public-methods)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3395:4: W0102: Dangerous default value {} as argument (dangerous-default-value)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3402:4: W0102: Dangerous default value {} as argument (dangerous-default-value)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3409:4: W0102: Dangerous default value {} as argument (dangerous-default-value)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3442:4: W0102: Dangerous default value {} as argument (dangerous-default-value)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3472:4: C0103: Argument name "x" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3472:4: C0103: Argument name "y" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3481:4: W0102: Dangerous default value {} as argument (dangerous-default-value)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3507:4: C0103: Argument name "x" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3507:4: C0103: Argument name "y" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3512:4: C0103: Argument name "x" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3512:4: C0103: Argument name "y" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3528:0: R0901: Too many ancestors (9/7) (too-many-ancestors)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3531:4: W0102: Dangerous default value {} as argument (dangerous-default-value)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3562:4: C0103: Argument name "op" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3583:8: R1705: Unnecessary "else" after "return" (no-else-return)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3588:4: R1710: Either all return statements in a function should return an expression, or none of them should. (inconsistent-return-statements)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3626:12: W0102: Dangerous default value result (builtins.list) as argument (dangerous-default-value)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3634:28: C0321: More than one statement on a single line (multiple-statements)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3721:4: W0102: Dangerous default value {} as argument (dangerous-default-value)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3740:4: C0103: Argument name "markName" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3751:4: C0103: Argument name "markName" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3767:4: W0102: Dangerous default value {} as argument (dangerous-default-value)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3767:4: C0103: Argument name "newPathName" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3788:4: C0103: Argument name "x" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3788:4: C0103: Argument name "y" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3792:4: C0103: Argument name "x" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3792:4: C0103: Argument name "y" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3798:4: R0913: Too many arguments (11/5) (too-many-arguments)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3805:21: C0321: More than one statement on a single line (multiple-statements)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3806:22: C0321: More than one statement on a single line (multiple-statements)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3807:18: C0321: More than one statement on a single line (multiple-statements)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3808:19: C0321: More than one statement on a single line (multiple-statements)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3809:19: C0321: More than one statement on a single line (multiple-statements)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3810:18: C0321: More than one statement on a single line (multiple-statements)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3811:18: C0321: More than one statement on a single line (multiple-statements)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3812:42: C0321: More than one statement on a single line (multiple-statements)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3815:22: C0321: More than one statement on a single line (multiple-statements)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3822:4: C0103: Argument name "tagName" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3828:4: C0103: Argument name "tagName" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3835:4: C0103: Argument name "tagName" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3844:4: C0103: Argument name "tagName" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3852:4: C0103: Argument name "tagName" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3862:4: C0103: Argument name "tagName" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3862:4: C0103: Argument name "belowThis" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3872:4: C0103: Argument name "tagName" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3879:4: C0103: Argument name "tagName" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3886:4: C0103: Argument name "tagName" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3886:4: C0103: Argument name "aboveThis" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3892:4: C0103: Argument name "tagName" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3897:4: C0103: Argument name "tagName" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3916:4: W0102: Dangerous default value {} as argument (dangerous-default-value)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3528:0: R0904: Too many public methods (51/20) (too-many-public-methods)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3932:0: R0903: Too few public methods (1/2) (too-few-public-methods)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3946:0: R0901: Too many ancestors (8/7) (too-many-ancestors)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3957:8: W0233: __init__ method from a non direct base class 'Widget' is called (non-parent-init-called)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3949:4: W0231: __init__ method from base class 'Menubutton' is not called (super-init-not-called)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3954:8: C0103: Variable name "kw" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3969:12: C0103: Variable name "v" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3995:8: C0103: Attribute name "tk" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3989:4: W0102: Dangerous default value {} as argument (dangerous-default-value)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:3999:23: C0321: More than one statement on a single line (multiple-statements)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:4000:17: C0321: More than one statement on a single line (multiple-statements)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:4002:15: C0103: Variable name "v" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:4004:16: C0103: Variable name "v" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:4004:20: E1101: Instance of 'Image' has no '_register' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:4009:23: C0321: More than one statement on a single line (multiple-statements)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:4028:15: C0103: Variable name "v" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:4030:33: C0321: More than one statement on a single line (multiple-statements)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:4032:20: C0103: Variable name "v" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:4032:24: E1101: Instance of 'Image' has no '_register' member (no-member)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:4056:4: W0102: Dangerous default value {} as argument (dangerous-default-value)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:4078:8: C0103: Variable name "destImage" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:4082:4: C0103: Argument name "x" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:4082:4: C0103: Argument name "y" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:4087:8: C0103: Variable name "destImage" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:4088:18: C0321: More than one statement on a single line (multiple-statements)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:4092:4: C0103: Argument name "x" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:4092:4: C0103: Argument name "y" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:4097:8: C0103: Variable name "destImage" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:4098:18: C0321: More than one statement on a single line (multiple-statements)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:4102:4: C0103: Argument name "x" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:4102:4: C0103: Argument name "y" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:4106:4: C0103: Argument name "to" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:4117:30: W0622: Redefining built-in 'format' (redefined-builtin)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:4127:4: C0103: Argument name "x" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:4127:4: C0103: Argument name "y" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:4132:4: C0103: Argument name "x" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:4132:4: C0103: Argument name "y" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:4140:4: W0102: Dangerous default value {} as argument (dangerous-default-value)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:4155:0: R0901: Too many ancestors (8/7) (too-many-ancestors)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:4158:4: W0102: Dangerous default value {} as argument (dangerous-default-value)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:4224:4: C0103: Argument name "x" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:4224:4: C0103: Argument name "y" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:4236:4: C0103: Argument name "s" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:4256:4: C0103: Argument name "x" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:4265:4: C0103: Argument name "x" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:4296:4: W0221: Parameters differ from overridden 'selection_clear' method (arguments-differ)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:4336:4: W0102: Dangerous default value {} as argument (dangerous-default-value)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:4360:4: W0102: Dangerous default value {} as argument (dangerous-default-value)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:4395:4: C0103: Argument name "x" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:4395:4: C0103: Argument name "y" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:4422:4: C0103: Argument name "x" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:4422:4: C0103: Argument name "y" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:4453:4: C0103: Argument name "x" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:4453:4: C0103: Argument name "y" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:4466:4: C0103: Argument name "tagOrId" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:4466:4: R1710: Either all return statements in a function should return an expression, or none of them should. (inconsistent-return-statements)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:4562:4: W0622: Redefining built-in 'quit' (redefined-builtin)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:38:0: C0411: standard import "from tkinter.constants import *" should be placed before "import _tkinter" (wrong-import-order)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/tkinter/__init__.py:39:0: C0411: standard import "import re" should be placed before "import _tkinter" (wrong-import-order)</pre>
<br />
<pre>------------------------------------</pre>
<pre>Your code has been rated at -2.79/10</pre>
<br />
  <!-- content end -->
</div>

<a href="https://github.com/e-m-b-a/emba" title="github.com/e-m-b-a/emba" target="_blank">
  <div id="buttonInfo" class="rectButtonVisible">
    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" focusable="false" width="40" height="40" style="-ms-transform: rotate(360deg); -webkit-transform: rotate(360deg); transform: rotate(360deg);" preserveAspectRatio="xMidYMid meet" viewBox="0 0 21 21"><g fill="none" fill-rule="evenodd" transform="translate(2 2)"><g stroke="white" stroke-linecap="round" stroke-linejoin="round"><circle cx="8.5" cy="8.5" r="8"/><path d="M8.5 12.5v-4h-1"/><path d="M7.5 12.5h2"/></g><circle cx="8.5" cy="5.5" fill="white" r="1"/></g></svg>
  </div>
</a>
<div id="buttonBack" class="nonClickable rectButtonVisible"><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" focusable="false" width="40" height="40" style="-ms-transform: rotate(360deg); -webkit-transform: rotate(360deg); transform: rotate(360deg);" preserveAspectRatio="xMidYMid meet" viewBox="0 0 21 21"><path d="M9.5 14.5l4-4l-4-4" fill="none" stroke="#444" stroke-linecap="round" stroke-linejoin="round"/></svg></div>
<div id="buttonForward" class="nonClickable rectButtonVisible"><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" focusable="false" width="40" height="40" style="-ms-transform: rotate(360deg); -webkit-transform: rotate(360deg); transform: rotate(360deg);" preserveAspectRatio="xMidYMid meet" viewBox="0 0 21 21"><path d="M11.5 14.5l-4-4l4-4" fill="none" stroke="#444" stroke-linecap="round" stroke-linejoin="round"/></svg></div> 
<div id="buttonDown" class="rectButton" onclick="scrollDown()"><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" focusable="false" width="40" height="40" style="-ms-transform: rotate(360deg); -webkit-transform: rotate(360deg); transform: rotate(360deg);" preserveAspectRatio="xMidYMid meet" viewBox="0 0 21 21"><g fill="none" fill-rule="evenodd" stroke="#fff" stroke-linecap="round" stroke-linejoin="round"><path d="M14.5 6.5l-4 4l-4-4"/><path d="M14.5 10.5l-4 4l-4-4"/></g></svg></div>
<div id="buttonUp" class="rectButton" onclick="scrollUp()"><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" focusable="false" width="40" height="40" style="-ms-transform: rotate(360deg); -webkit-transform: rotate(360deg); transform: rotate(360deg);" preserveAspectRatio="xMidYMid meet" viewBox="0 0 21 21"><g fill="none" fill-rule="evenodd" stroke="#fff" stroke-linecap="round" stroke-linejoin="round"><path d="M6.5 14.5l4-4l4 4"/><path d="M6.5 10.5l4-4l4 4"/></g></svg></div> 

<script>
window.onload = function () {
  var buttons = document.getElementsByClassName("rectButton");
  for (let i=0; i<buttons.length; i++) {
    buttons[i].style.visibility = "visible";
  }
  var buttonDown = document.getElementById("buttonDown");
  buttonDown.classList.add('rectButtonVisible');
  buttonDown.classList.remove('rectButton');

  var buttonUp = document.getElementById("buttonUp");
  buttonUp.classList.add('rectButtonVisible');
  buttonUp.classList.remove('rectButton');
    
  var buttonSizer = document.getElementById("buttonSizer");
  buttonSizer.innerHTML = '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" focusable="false" width="40" height="40" style="-ms-transform: rotate(360deg); -webkit-transform: rotate(360deg); transform: rotate(360deg);" preserveAspectRatio="xMidYMid meet" viewBox="0 0 21 21"><g fill="none" fill-rule="evenodd" stroke="white" stroke-linecap="round" stroke-linejoin="round"><path d="M9.5 16.5v-4.978l-5-.022"/><path d="M18.5 2.5l-7 7"/><path d="M16.5 9.5l-5 .023V4.5"/><path d="M9.5 11.5l-7 7"/></g></svg>';
  if (document.getElementById("buttonTime") !== null) {
    var buttonTime = document.getElementById("buttonTime");
    buttonTime.style.bottom = "50px";
  }
  document.getElementById("expand").value = "+ Show more results";
  document.getElementById("expand").className += " expand";
}

function openNav() {
  document.getElementById("sidenav").style.width = "250px";
  document.getElementById("main").style.marginLeft = "250px";
  document.getElementById("nav").style.visibility = "visible";
}

function closeNav() {
  document.getElementById("sidenav").style.width = "50px";
  document.getElementById("sidenav").scrollTop = 0;
  document.getElementById("main").style.marginLeft = "50px";
  document.getElementById("nav").style.visibility = "hidden";
}

function scrollDown() {
  window.scrollTo(0,document.body.scrollHeight);
}

function scrollUp() {
  window.scrollTo(0,0);
}

function buttonNav() {
  var button = document.getElementById("buttonSizer");
  if ( button.classList.contains('buttonOpen') ) {
    button.classList.remove('buttonOpen');
    button.classList.add('buttonClose');
    button.innerHTML = '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" focusable="false" width="40" height="40" style="-ms-transform: rotate(360deg); -webkit-transform: rotate(360deg); transform: rotate(360deg);" preserveAspectRatio="xMidYMid meet" viewBox="0 0 21 21"><g fill="none" fill-rule="evenodd" stroke="white" stroke-linecap="round" stroke-linejoin="round"><path d="M9.5 16.5v-4.978l-5-.022"/><path d="M18.5 2.5l-7 7"/><path d="M16.5 9.5l-5 .023V4.5"/><path d="M9.5 11.5l-7 7"/></g></svg>';
    openNav();
  } else if( button.classList.contains('buttonClose') ) {
    button.classList.remove('buttonClose');
    button.classList.add('buttonOpen');
    button.innerHTML = '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" focusable="false" width="40" height="40" style="-ms-transform: rotate(360deg); -webkit-transform: rotate(360deg); transform: rotate(360deg);" preserveAspectRatio="xMidYMid meet" viewBox="0 0 21 21"><g fill="none" fill-rule="evenodd" stroke="white" stroke-linecap="round" stroke-linejoin="round"><path d="M18.5 7.5v-5h-5"/><path d="M18.5 2.5l-6 5.929"/><path d="M7.5 18.5l-5 .023V13.5"/><path d="M8.5 12.5l-6 6"/></g></svg>';
    closeNav();
  };
}

document.onkeydown = function(e) {
    switch (e.keyCode) {
      case 37:
        document.getElementById("buttonForward").parentNode.click(); 
        break;
      case 39:
        document.getElementById("buttonBack").parentNode.click();       
        break;
    }
};
</script>

</body>
</html>
