************* Module gevent.tests.test__compat
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__compat.py:16:4: C0103: Method name "_callFUT" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__compat.py:17:8: C0415: Import outside toplevel (gevent._compat._fspath) (import-outside-toplevel)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__compat.py:16:4: R0201: Method could be a function (no-self-use)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__compat.py:21:8: C0103: Variable name "s" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__compat.py:25:8: C0103: Variable name "s" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__compat.py:28:4: C0103: Method name "test_None" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__compat.py:39:4: C0103: Method name "test_failing_path_AttributeError" doesn't conform to snake_case naming style (invalid-name)

-----------------------------------
Your code has been rated at 8.25/10

