************* Module email.contentmanager
/log/firmware/firmware/usr/lib/python3.8/email/contentmanager.py:20:8: W0621: Redefining name 'maintype' from outer scope (line 73) (redefined-outer-name)
/log/firmware/firmware/usr/lib/python3.8/email/contentmanager.py:41:12: W0621: Redefining name 'typ' from outer scope (line 249) (redefined-outer-name)
/log/firmware/firmware/usr/lib/python3.8/email/contentmanager.py:39:32: W0613: Unused argument 'msg' (unused-argument)
/log/firmware/firmware/usr/lib/python3.8/email/contentmanager.py:95:22: W0621: Redefining name 'maintype' from outer scope (line 73) (redefined-outer-name)
/log/firmware/firmware/usr/lib/python3.8/email/contentmanager.py:95:32: W0621: Redefining name 'subtype' from outer scope (line 79) (redefined-outer-name)
/log/firmware/firmware/usr/lib/python3.8/email/contentmanager.py:99:12: C0103: Variable name "mp" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/email/contentmanager.py:145:30: C0321: More than one statement on a single line (multiple-statements)
/log/firmware/firmware/usr/lib/python3.8/email/contentmanager.py:146:28: C0321: More than one statement on a single line (multiple-statements)
/log/firmware/firmware/usr/lib/python3.8/email/contentmanager.py:147:7: C0121: Comparison 'cte == None' should be 'cte is None' (singleton-comparison)
/log/firmware/firmware/usr/lib/python3.8/email/contentmanager.py:181:34: W0621: Redefining name 'subtype' from outer scope (line 79) (redefined-outer-name)
/log/firmware/firmware/usr/lib/python3.8/email/contentmanager.py:181:0: R0913: Too many arguments (10/5) (too-many-arguments)
/log/firmware/firmware/usr/lib/python3.8/email/contentmanager.py:195:38: W0621: Redefining name 'subtype' from outer scope (line 79) (redefined-outer-name)
/log/firmware/firmware/usr/lib/python3.8/email/contentmanager.py:195:0: R0913: Too many arguments (9/5) (too-many-arguments)
/log/firmware/firmware/usr/lib/python3.8/email/contentmanager.py:228:33: W0621: Redefining name 'maintype' from outer scope (line 73) (redefined-outer-name)
/log/firmware/firmware/usr/lib/python3.8/email/contentmanager.py:228:43: W0621: Redefining name 'subtype' from outer scope (line 79) (redefined-outer-name)
/log/firmware/firmware/usr/lib/python3.8/email/contentmanager.py:228:0: R0913: Too many arguments (10/5) (too-many-arguments)

-----------------------------------
Your code has been rated at 9.07/10

