************* Module aiocoap.oscore
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:1:0: C0302: Too many lines in module (1732/1000) (too-many-lines)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:21:0: C0410: Multiple imports on one line (os, os.path) (multiple-imports)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:29:0: E0611: No name 'GET' in module 'aiocoap.numbers' (no-name-in-module)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:29:0: E0611: No name 'POST' in module 'aiocoap.numbers' (no-name-in-module)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:29:0: E0611: No name 'FETCH' in module 'aiocoap.numbers' (no-name-in-module)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:29:0: E0611: No name 'CHANGED' in module 'aiocoap.numbers' (no-name-in-module)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:29:0: E0611: No name 'UNAUTHORIZED' in module 'aiocoap.numbers' (no-name-in-module)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:59:0: R0903: Too few public methods (0/2) (too-few-public-methods)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:92:4: W0231: __init__ method from base class 'ProtectionInvalid' is not called (super-init-not-called)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:92:4: W0231: __init__ method from base class 'RenderableError' is not called (super-init-not-called)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:128:8: R1705: Unnecessary "else" after "return" (no-else-return)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:109:0: R0903: Too few public methods (1/2) (too-few-public-methods)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:134:0: C0103: Argument name "a" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:134:0: C0103: Argument name "b" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:142:4: C0103: Argument name "iv" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:142:4: E0213: Method should have "self" as first argument (no-self-argument)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:146:4: C0103: Argument name "iv" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:146:4: E0213: Method should have "self" as first argument (no-self-argument)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:158:0: C0103: Class name "AES_CCM" doesn't conform to PascalCase naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:163:32: E1101: Class 'AES_CCM' has no 'tag_bytes' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:168:36: E1101: Class 'AES_CCM' has no 'tag_bytes' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:170:12: W0707: Consider explicitly re-raising using the 'from' keyword (raise-missing-from)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:172:0: C0103: Class name "AES_CCM_16_64_128" doesn't conform to PascalCase naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:179:0: C0103: Class name "AES_CCM_16_64_256" doesn't conform to PascalCase naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:186:0: C0103: Class name "AES_CCM_64_64_128" doesn't conform to PascalCase naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:193:0: C0103: Class name "AES_CCM_64_64_256" doesn't conform to PascalCase naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:200:0: C0103: Class name "AES_CCM_16_128_128" doesn't conform to PascalCase naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:207:0: C0103: Class name "AES_CCM_16_128_256" doesn't conform to PascalCase naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:214:0: C0103: Class name "AES_CCM_64_128_128" doesn't conform to PascalCase naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:221:0: C0103: Class name "AES_CCM_64_128_256" doesn't conform to PascalCase naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:229:0: C0103: Class name "AES_GCM" doesn't conform to PascalCase naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:243:12: W0707: Consider explicitly re-raising using the 'from' keyword (raise-missing-from)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:279:12: W0707: Consider explicitly re-raising using the 'from' keyword (raise-missing-from)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:327:4: W0221: Parameters differ from overridden 'sign' method (arguments-differ)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:331:4: W0221: Parameters differ from overridden 'verify' method (arguments-differ)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:336:12: W0707: Consider explicitly re-raising using the 'from' keyword (raise-missing-from)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:372:0: C0103: Class name "ECDSA_SHA256_P256" doesn't conform to PascalCase naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:375:4: C0103: Argument name "x" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:375:4: C0103: Argument name "y" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:375:4: R0201: Method could be a function (no-self-use)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:383:4: C0103: Argument name "x" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:383:4: C0103: Argument name "y" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:383:4: C0103: Argument name "d" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:390:4: W0221: Parameters differ from overridden 'sign' method (arguments-differ)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:392:9: C0103: Variable name "r" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:392:12: C0103: Variable name "s" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:396:4: W0221: Parameters differ from overridden 'verify' method (arguments-differ)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:397:8: C0103: Variable name "r" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:398:8: C0103: Variable name "s" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:399:8: C0103: Variable name "r" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:400:8: C0103: Variable name "s" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:405:12: W0707: Consider explicitly re-raising using the 'from' keyword (raise-missing-from)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:472:8: C0103: Variable name "s" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:473:26: E1101: Instance of 'BaseSecurityContext' has no 'algorithm' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:481:27: E1101: Instance of 'BaseSecurityContext' has no 'common_iv' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:494:8: W0621: Redefining name 'algorithms' from outer scope (line 421) (redefined-outer-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:494:22: E1101: Instance of 'BaseSecurityContext' has no 'algorithm' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:496:30: E1101: Instance of 'BaseSecurityContext' has no 'alg_countersign' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:507:32: E1101: Instance of 'BaseSecurityContext' has no 'id_context' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:454:0: R0903: Too few public methods (0/2) (too-few-public-methods)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:555:12: C0103: Variable name "s" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:580:4: R0914: Too many local variables (16/15) (too-many-locals)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:609:36: E1101: Instance of 'CanProtect' has no 'sender_id' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:611:44: E1101: Instance of 'CanProtect' has no 'sender_id' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:614:19: E1101: Instance of 'CanProtect' has no 'id_context' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:615:52: E1101: Instance of 'CanProtect' has no 'id_context' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:620:40: E1101: Instance of 'CanProtect' has no 'sender_id' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:622:14: W0212: Access to a protected member _build_encrypt0_structure of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:622:14: E1101: Instance of 'CanProtect' has no 'algorithm' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:626:21: E1101: Instance of 'CanProtect' has no 'algorithm' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:633:8: E0237: Assigning to attribute 'object_security' not defined in class slots (assigning-non-slot)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:642:23: E1101: Instance of 'CanProtect' has no 'alg_countersign' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:642:84: E1101: Instance of 'CanProtect' has no 'private_key' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:659:15: E1101: Instance of 'CanProtect' has no 'sender_key' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:652:30: W0613: Unused argument 'outer_message' (unused-argument)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:652:45: W0613: Unused argument 'aad' (unused-argument)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:652:50: W0613: Unused argument 'plaintext' (unused-argument)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:652:61: W0613: Unused argument 'request_id' (unused-argument)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:661:4: R0201: Method could be a function (no-self-use)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:727:50: E1101: Instance of 'CanProtect' has no 'sender_id' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:736:17: E1101: Instance of 'CanProtect' has no 'sender_sequence_number' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:739:8: E1101: Instance of 'CanProtect' has no 'sender_sequence_number' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:748:8: E0704: The raise statement is not inside an except clause (misplaced-bare-raise)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:750:36: W0613: Unused argument 'unprotected_bag' (unused-argument)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:762:4: R0914: Too many local variables (22/15) (too-many-locals)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:777:45: E1101: Instance of 'CanUnprotect' has no 'id_context' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:777:65: E1101: Instance of 'CanUnprotect' has no 'id_context' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:781:37: E1101: Instance of 'CanUnprotect' has no 'recipient_id' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:781:59: E1101: Instance of 'CanUnprotect' has no 'recipient_id' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:796:60: E1101: Instance of 'CanUnprotect' has no 'recipient_id' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:801:23: E1101: Instance of 'CanUnprotect' has no 'recipient_replay_window' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:803:25: E1101: Instance of 'CanUnprotect' has no 'recipient_replay_window' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:806:48: E1101: Instance of 'CanUnprotect' has no 'echo_recovery' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:810:48: E1101: Instance of 'CanUnprotect' has no 'recipient_id' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:814:34: E1101: Instance of 'CanUnprotect' has no 'alg_countersign' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:816:16: W0707: Consider explicitly re-raising using the 'from' keyword (raise-missing-from)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:829:29: E1101: Instance of 'CanUnprotect' has no 'algorithm' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:837:20: E1101: Instance of 'CanUnprotect' has no 'algorithm' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:842:12: E1101: Instance of 'CanUnprotect' has no 'recipient_replay_window' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:847:84: E1101: Instance of 'CanUnprotect' has no 'recipient_public_key' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:854:29: E1101: Instance of 'CanUnprotect' has no 'recipient_replay_window' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:855:16: E1101: Instance of 'CanUnprotect' has no 'echo_recovery' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:860:51: E1101: Instance of 'CanUnprotect' has no 'echo_recovery' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:861:20: E1101: Instance of 'CanUnprotect' has no 'recipient_replay_window' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:864:87: E1101: Instance of 'CanUnprotect' has no 'echo_recovery' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:879:20: E1101: Instance of 'CanUnprotect' has no 'recipient_replay_window' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:882:12: E0702: Raising NoneType while only classes or instances are allowed (raising-bad-type)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:886:16: E0237: Assigning to attribute 'observe' not defined in class slots (assigning-non-slot)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:893:16: E0237: Assigning to attribute 'observe' not defined in class slots (assigning-non-slot)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:762:4: R0912: Too many branches (27/12) (too-many-branches)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:762:4: R0915: Too many statements (73/50) (too-many-statements)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:902:15: E1101: Instance of 'CanUnprotect' has no 'recipient_key' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:897:33: W0613: Unused argument 'protected_message' (unused-argument)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:934:12: C0103: Variable name "s" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:975:28: E1101: Instance of 'SecurityContextUtils' has no 'algorithm' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:975:60: E1101: Instance of 'SecurityContextUtils' has no 'algorithm' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:979:12: E1101: Instance of 'SecurityContextUtils' has no 'id_context' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:980:12: E1101: Instance of 'SecurityContextUtils' has no 'algorithm' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:985:26: E1101: Instance of 'SecurityContextUtils' has no 'hashfun' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:999:64: E1101: Instance of 'SecurityContextUtils' has no 'sender_id' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:1000:67: E1101: Instance of 'SecurityContextUtils' has no 'recipient_id' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:1016:46: E1101: Instance of 'SecurityContextUtils' has no 'recipient_id' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:1016:111: E1101: Instance of 'SecurityContextUtils' has no 'id_context' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:1006:4: R1710: Either all return statements in a function should return an expression, or none of them should. (inconsistent-return-statements)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:999:8: W0201: Attribute 'sender_key' defined outside __init__ (attribute-defined-outside-init)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:1000:8: W0201: Attribute 'recipient_key' defined outside __init__ (attribute-defined-outside-init)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:1002:8: W0201: Attribute 'common_iv' defined outside __init__ (attribute-defined-outside-init)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:1126:0: R0902: Too many instance attributes (15/7) (too-many-instance-attributes)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:1212:67: C0103: Variable name "f" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:1251:70: C0103: Variable name "f" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:1275:20: W0707: Consider explicitly re-raising using the 'from' keyword (raise-missing-from)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:1205:4: R0912: Too many branches (13/12) (too-many-branches)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:1312:12: W0201: Attribute 'replay_window_persisted' defined outside __init__ (attribute-defined-outside-init)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:1339:8: W0201: Attribute 'replay_window_persisted' defined outside __init__ (attribute-defined-outside-init)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:1376:0: R0902: Too many instance attributes (13/7) (too-many-instance-attributes)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:1389:4: R0913: Too many arguments (10/5) (too-many-arguments)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:1402:12: C0103: Variable name "w" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:1438:12: W0707: Consider explicitly re-raising using the 'from' keyword (raise-missing-from)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:1440:8: R1705: Unnecessary "else" after "return" (no-else-return)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:1451:12: R1705: Unnecessary "elif" after "return" (no-else-return)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:1445:4: R1710: Either all return statements in a function should return an expression, or none of them should. (inconsistent-return-statements)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:1466:0: W0223: Method 'private_key' is abstract in class 'GroupContext' but is not overridden (abstract-method)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:1554:8: R1705: Unnecessary "else" after "return" (no-else-return)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:1609:8: C0103: Variable name "h" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:1652:8: R0201: Method could be a function (no-self-use)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:1655:8: R0201: Method could be a function (no-self-use)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:1697:8: C0103: Variable name "h" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:1730:27: W0212: Access to a protected member _extract_encrypted0 of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/site-packages/aiocoap/oscore.py:22:0: W0611: Unused import warnings (unused-import)

-----------------------------------
Your code has been rated at 5.09/10

