************* Module asyncio.base_tasks
/log/firmware/firmware/usr/lib/python3.8/asyncio/base_tasks.py:9:11: W0212: Access to a protected member _future_repr_info of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/asyncio/base_tasks.py:11:7: W0212: Access to a protected member _must_cancel of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/asyncio/base_tasks.py:17:11: W0212: Access to a protected member _format_coroutine of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/asyncio/base_tasks.py:17:40: W0212: Access to a protected member _coro of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/asyncio/base_tasks.py:20:7: W0212: Access to a protected member _fut_waiter of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/asyncio/base_tasks.py:21:35: W0212: Access to a protected member _fut_waiter of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/asyncio/base_tasks.py:29:8: C0103: Variable name "f" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/asyncio/base_tasks.py:29:12: W0212: Access to a protected member _coro of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/asyncio/base_tasks.py:31:8: C0103: Variable name "f" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/asyncio/base_tasks.py:31:12: W0212: Access to a protected member _coro of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/asyncio/base_tasks.py:39:12: C0103: Variable name "f" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/asyncio/base_tasks.py:41:9: W0212: Access to a protected member _exception of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/asyncio/base_tasks.py:42:8: C0103: Variable name "tb" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/asyncio/base_tasks.py:42:13: W0212: Access to a protected member _exception of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/asyncio/base_tasks.py:49:12: C0103: Variable name "tb" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/asyncio/base_tasks.py:56:8: C0103: Variable name "f" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/asyncio/base_tasks.py:58:8: C0103: Variable name "co" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/asyncio/base_tasks.py:67:10: W0212: Access to a protected member _exception of a client class (protected-access)

-----------------------------------
Your code has been rated at 7.10/10

