************* Module unittest.async_case
/log/firmware/firmware/usr/lib/python3.8/unittest/async_case.py:36:8: C0103: Attribute name "_asyncioTestLoop" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/unittest/async_case.py:37:8: C0103: Attribute name "_asyncioCallsQueue" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/unittest/async_case.py:118:8: C0103: Attribute name "_asyncioCallsTask" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/unittest/async_case.py:39:4: C0103: Method name "asyncSetUp" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/unittest/async_case.py:42:4: C0103: Method name "asyncTearDown" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/unittest/async_case.py:45:4: C0103: Method name "addAsyncCleanup" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/unittest/async_case.py:71:4: W0221: Parameters differ from overridden '_callCleanup' method (arguments-differ)
/log/firmware/firmware/usr/lib/python3.8/unittest/async_case.py:74:4: C0103: Method name "_callAsync" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/unittest/async_case.py:82:4: C0103: Method name "_callMaybeAsync" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/unittest/async_case.py:85:8: R1705: Unnecessary "else" after "return" (no-else-return)
/log/firmware/firmware/usr/lib/python3.8/unittest/async_case.py:92:4: C0103: Method name "_asyncioLoopRunner" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/unittest/async_case.py:105:12: W0706: The except handler raises immediately (try-except-raise)
/log/firmware/firmware/usr/lib/python3.8/unittest/async_case.py:107:19: W0703: Catching too general exception Exception (broad-except)
/log/firmware/firmware/usr/lib/python3.8/unittest/async_case.py:111:4: C0103: Method name "_setupAsyncioLoop" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/unittest/async_case.py:121:4: C0103: Method name "_tearDownAsyncioLoop" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/unittest/async_case.py:118:8: W0201: Attribute '_asyncioCallsTask' defined outside __init__ (attribute-defined-outside-init)

-----------------------------------
Your code has been rated at 8.26/10

