************* Module uuid
/log/firmware/firmware/usr/lib/python3.8/uuid.py:385:0: C0325: Unnecessary parens after 'not' keyword (superfluous-parens)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:66:0: C0103: Class name "int_" doesn't conform to PascalCase naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:67:0: C0103: Class name "bytes_" doesn't conform to PascalCase naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:71:4: C0103: Constant name "safe" doesn't conform to UPPER_CASE naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:72:4: C0103: Constant name "unsafe" doesn't conform to UPPER_CASE naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:73:4: C0103: Constant name "unknown" doesn't conform to UPPER_CASE naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:128:17: E0242: Value 'int' in slots conflicts with class variable (class-variable-slots-conflict)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:130:23: W0622: Redefining built-in 'hex' (redefined-builtin)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:130:33: W0622: Redefining built-in 'bytes' (redefined-builtin)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:131:23: W0622: Redefining built-in 'int' (redefined-builtin)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:130:4: R0913: Too many arguments (7/5) (too-many-arguments)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:130:4: R0912: Too many branches (19/12) (too-many-branches)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:217:8: C0103: Variable name "d" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:218:11: E1101: Instance of 'UUID' has no 'is_safe' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:221:27: E1101: Instance of 'UUID' has no 'is_safe' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:272:8: W0622: Redefining built-in 'hex' (redefined-builtin)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:282:8: W0622: Redefining built-in 'bytes' (redefined-builtin)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:335:8: R1705: Unnecessary "elif" after "return" (no-else-return)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:345:4: R1710: Either all return statements in a function should return an expression, or none of them should. (inconsistent-return-statements)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:351:4: W0621: Redefining name 'os' from outer scope (line 47) (redefined-outer-name)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:351:4: W0404: Reimport 'os' (imported line 47) (reimported)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:351:4: C0415: Import outside toplevel (os, shutil, subprocess) (import-outside-toplevel)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:351:4: C0410: Multiple imports on one line (os, shutil, subprocess) (multiple-imports)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:396:16: C0200: Consider using enumerate instead of iterating with range and len (consider-using-enumerate)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:435:4: W0621: Redefining name 'os' from outer scope (line 47) (redefined-outer-name)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:435:4: W0404: Reimport 'os' (imported line 47) (reimported)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:435:4: C0415: Import outside toplevel (os, socket) (import-outside-toplevel)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:435:4: C0410: Multiple imports on one line (os, socket) (multiple-imports)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:495:4: W0621: Redefining name 'os' from outer scope (line 47) (redefined-outer-name)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:505:8: W0622: Redefining built-in 'dir' (redefined-builtin)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:495:4: W0404: Reimport 'os' (imported line 47) (reimported)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:495:4: C0415: Import outside toplevel (os, re, subprocess) (import-outside-toplevel)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:495:4: C0410: Multiple imports on one line (os, re, subprocess) (multiple-imports)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:503:4: W0702: No exception type(s) specified (bare-except)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:499:8: C0415: Import outside toplevel (ctypes) (import-outside-toplevel)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:548:8: W0622: Redefining built-in 'bytes' (redefined-builtin)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:525:4: C0415: Import outside toplevel (win32wnet, netbios) (import-outside-toplevel)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:525:4: C0410: Multiple imports on one line (win32wnet, netbios) (multiple-imports)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:530:4: W0212: Access to a protected member _pack of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:533:4: W0212: Access to a protected member _unpack of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:547:8: W0212: Access to a protected member _unpack of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:558:0: C0103: Constant name "_generate_time_safe" doesn't conform to UPPER_CASE naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:558:22: C0103: Constant name "_UuidCreate" doesn't conform to UPPER_CASE naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:559:0: C0103: Constant name "_has_uuid_generate_time_safe" doesn't conform to UPPER_CASE naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:572:4: C0103: Constant name "_generate_time_safe" doesn't conform to UPPER_CASE naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:572:4: C0103: Constant name "_UuidCreate" doesn't conform to UPPER_CASE naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:572:4: C0103: Constant name "_has_uuid_generate_time_safe" doesn't conform to UPPER_CASE naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:572:4: W0603: Using the global statement (global-statement)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:646:11: W0703: Catching too general exception Exception (broad-except)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:597:8: C0415: Import outside toplevel (ctypes) (import-outside-toplevel)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:598:8: C0415: Import outside toplevel (ctypes.util) (import-outside-toplevel)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:608:19: W0703: Catching too general exception Exception (broad-except)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:611:12: R1723: Unnecessary "elif" after "break" (no-else-break)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:616:26: W0640: Cell variable _uuid_generate_time_safe defined in loop (cell-var-from-loop)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:627:20: W0640: Cell variable _uuid_generate_time defined in loop (cell-var-from-loop)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:641:8: W0702: No exception type(s) specified (bare-except)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:647:8: C0415: Import outside toplevel (warnings) (import-outside-toplevel)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:661:4: C0415: Import outside toplevel (ctypes) (import-outside-toplevel)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:659:0: R1710: Either all return statements in a function should return an expression, or none of them should. (inconsistent-return-statements)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:679:4: C0415: Import outside toplevel (random) (import-outside-toplevel)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:707:0: C0103: Constant name "_node" doesn't conform to UPPER_CASE naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:717:4: C0103: Constant name "_node" doesn't conform to UPPER_CASE naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:717:4: W0603: Using the global statement (global-statement)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:724:8: W0702: No exception type(s) specified (bare-except)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:709:0: R1710: Either all return statements in a function should return an expression, or none of them should. (inconsistent-return-statements)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:709:15: W0613: Unused argument 'getters' (unused-argument)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:731:0: C0103: Constant name "_last_timestamp" doesn't conform to UPPER_CASE naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:750:4: C0103: Constant name "_last_timestamp" doesn't conform to UPPER_CASE naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:750:4: W0603: Using the global statement (global-statement)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:751:4: C0415: Import outside toplevel (time) (import-outside-toplevel)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:760:8: C0415: Import outside toplevel (random) (import-outside-toplevel)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:775:4: W0622: Redefining built-in 'hash' (redefined-builtin)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:774:4: C0415: Import outside toplevel (hashlib.md5) (import-outside-toplevel)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:785:4: W0622: Redefining built-in 'hash' (redefined-builtin)
/log/firmware/firmware/usr/lib/python3.8/uuid.py:784:4: C0415: Import outside toplevel (hashlib.sha1) (import-outside-toplevel)

-----------------------------------
Your code has been rated at 7.96/10

