************* Module wtforms.fields.choices
/log/firmware/firmware/usr/lib/python3.8/site-packages/wtforms/fields/choices.py:37:4: R0201: Method could be a function (no-self-use)
/log/firmware/firmware/usr/lib/python3.8/site-packages/wtforms/fields/choices.py:68:4: R0913: Too many arguments (6/5) (too-many-arguments)
/log/firmware/firmware/usr/lib/python3.8/site-packages/wtforms/fields/choices.py:121:12: W0201: Attribute 'data' defined outside __init__ (attribute-defined-outside-init)
/log/firmware/firmware/usr/lib/python3.8/site-packages/wtforms/fields/choices.py:123:12: W0201: Attribute 'data' defined outside __init__ (attribute-defined-outside-init)
/log/firmware/firmware/usr/lib/python3.8/site-packages/wtforms/fields/choices.py:130:12: W0201: Attribute 'data' defined outside __init__ (attribute-defined-outside-init)
/log/firmware/firmware/usr/lib/python3.8/site-packages/wtforms/fields/choices.py:172:12: W0201: Attribute 'data' defined outside __init__ (attribute-defined-outside-init)
/log/firmware/firmware/usr/lib/python3.8/site-packages/wtforms/fields/choices.py:174:12: W0201: Attribute 'data' defined outside __init__ (attribute-defined-outside-init)
/log/firmware/firmware/usr/lib/python3.8/site-packages/wtforms/fields/choices.py:178:12: W0201: Attribute 'data' defined outside __init__ (attribute-defined-outside-init)

-----------------------------------
Your code has been rated at 9.30/10

