************* Module gevent._socket3
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/_socket3.py:27:17: W0212: Access to a protected member _implements of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/_socket3.py:36:0: R0205: Class '_closedsocket' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/_socket3.py:39:31: W0622: Redefining built-in 'type' (redefined-builtin)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/_socket3.py:39:4: R0913: Too many arguments (6/5) (too-many-arguments)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/_socket3.py:46:4: R0201: Method could be a function (no-self-use)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/_socket3.py:89:0: C0103: Class name "socket" doesn't conform to PascalCase naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/_socket3.py:114:43: W0622: Redefining built-in 'type' (redefined-builtin)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/_socket3.py:123:38: W0622: Redefining built-in 'type' (redefined-builtin)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/_socket3.py:169:12: C0103: Variable name "s" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/_socket3.py:175:12: C0103: Variable name "s" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/_socket3.py:178:12: C0103: Variable name "s" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/_socket3.py:187:4: R0201: Method could be a function (no-self-use)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/_socket3.py:198:8: C0103: Variable name "fd" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/_socket3.py:212:16: C0103: Variable name "fd" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/_socket3.py:238:12: C0103: Variable name "c" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/_socket3.py:306:8: W0622: Redefining built-in 'type' (redefined-builtin)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/_socket3.py:417:14: W0212: Access to a protected member _GiveupOnSendfile of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/_socket3.py:415:4: R0201: Method could be a function (no-self-use)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/_socket3.py:495:19: E1101: Module 'os' has no 'get_handle_inheritable' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/_socket3.py:498:12: E1101: Module 'os' has no 'set_handle_inheritable' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/_socket3.py:514:0: C0103: Argument name "fd" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/_socket3.py:514:23: W0622: Redefining built-in 'type' (redefined-builtin)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/_socket3.py:538:32: W0622: Redefining built-in 'type' (redefined-builtin)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/_socket3.py:555:8: C0103: Variable name "a" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/_socket3.py:555:11: C0103: Variable name "b" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/_socket3.py:556:8: C0103: Variable name "a" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/_socket3.py:557:8: C0103: Variable name "b" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/_socket3.py:569:35: W0622: Redefining built-in 'type' (redefined-builtin)
************* Module gevent._socketcommon
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/_socketcommon.py:6:4: E0603: Undefined variable name 'create_connection' in __all__ (undefined-all-variable)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/_socketcommon.py:26:4: E0603: Undefined variable name 'cancel_wait' in __all__ (undefined-all-variable)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/_socketcommon.py:27:4: E0603: Undefined variable name 'wait_read' in __all__ (undefined-all-variable)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/_socketcommon.py:28:4: E0603: Undefined variable name 'wait_write' in __all__ (undefined-all-variable)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/_socketcommon.py:29:4: E0603: Undefined variable name 'wait_readwrite' in __all__ (undefined-all-variable)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/_socketcommon.py:34:4: E0603: Undefined variable name 'error' in __all__ (undefined-all-variable)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/_socketcommon.py:35:4: E0603: Undefined variable name 'gaierror' in __all__ (undefined-all-variable)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/_socketcommon.py:36:4: E0603: Undefined variable name 'herror' in __all__ (undefined-all-variable)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/_socketcommon.py:37:4: E0603: Undefined variable name 'htonl' in __all__ (undefined-all-variable)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/_socketcommon.py:38:4: E0603: Undefined variable name 'htons' in __all__ (undefined-all-variable)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/_socketcommon.py:39:4: E0603: Undefined variable name 'ntohl' in __all__ (undefined-all-variable)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/_socketcommon.py:40:4: E0603: Undefined variable name 'ntohs' in __all__ (undefined-all-variable)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/_socketcommon.py:41:4: E0603: Undefined variable name 'inet_aton' in __all__ (undefined-all-variable)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/_socketcommon.py:42:4: E0603: Undefined variable name 'inet_ntoa' in __all__ (undefined-all-variable)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/_socketcommon.py:43:4: E0603: Undefined variable name 'inet_pton' in __all__ (undefined-all-variable)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/_socketcommon.py:44:4: E0603: Undefined variable name 'inet_ntop' in __all__ (undefined-all-variable)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/_socketcommon.py:45:4: E0603: Undefined variable name 'timeout' in __all__ (undefined-all-variable)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/_socketcommon.py:46:4: E0603: Undefined variable name 'gethostname' in __all__ (undefined-all-variable)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/_socketcommon.py:47:4: E0603: Undefined variable name 'getprotobyname' in __all__ (undefined-all-variable)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/_socketcommon.py:48:4: E0603: Undefined variable name 'getservbyname' in __all__ (undefined-all-variable)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/_socketcommon.py:49:4: E0603: Undefined variable name 'getservbyport' in __all__ (undefined-all-variable)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/_socketcommon.py:50:4: E0603: Undefined variable name 'getdefaulttimeout' in __all__ (undefined-all-variable)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/_socketcommon.py:51:4: E0603: Undefined variable name 'setdefaulttimeout' in __all__ (undefined-all-variable)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/_socketcommon.py:53:4: E0603: Undefined variable name 'errorTab' in __all__ (undefined-all-variable)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/_socket3.py:18:0: C0411: standard import "from os import dup" should be placed before "from gevent import _socketcommon" (wrong-import-order)

-----------------------------------
Your code has been rated at 5.40/10

