************* Module site
/log/firmware/firmware/usr/lib/python3.8/site.py:92:4: W0622: Redefining built-in 'dir' (redefined-builtin)
/log/firmware/firmware/usr/lib/python3.8/site.py:102:8: C0103: Variable name "m" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site.py:123:8: W0622: Redefining built-in 'dir' (redefined-builtin)
/log/firmware/firmware/usr/lib/python3.8/site.py:121:4: C0103: Variable name "L" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site.py:137:4: C0103: Variable name "d" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site.py:172:16: W0622: Redefining built-in 'dir' (redefined-builtin)
/log/firmware/firmware/usr/lib/python3.8/site.py:160:8: C0103: Variable name "f" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site.py:164:12: C0103: Variable name "n" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site.py:176:19: W0703: Catching too general exception Exception (broad-except)
/log/firmware/firmware/usr/lib/python3.8/site.py:169:20: W0122: Use of exec (exec-used)
/log/firmware/firmware/usr/lib/python3.8/site.py:179:16: C0415: Import outside toplevel (traceback) (import-outside-toplevel)
/log/firmware/firmware/usr/lib/python3.8/site.py:181:20: W0621: Redefining name 'line' from outer scope (line 164) (redefined-outer-name)
/log/firmware/firmware/usr/lib/python3.8/site.py:148:0: R1710: Either all return statements in a function should return an expression, or none of them should. (inconsistent-return-statements)
/log/firmware/firmware/usr/lib/python3.8/site.py:190:0: R1710: Either all return statements in a function should return an expression, or none of them should. (inconsistent-return-statements)
/log/firmware/firmware/usr/lib/python3.8/site.py:252:34: E1120: No value for argument 'a' in function call (no-value-for-parameter)
/log/firmware/firmware/usr/lib/python3.8/site.py:258:36: W0212: Access to a protected member _framework of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/site.py:259:40: W0212: Access to a protected member _framework of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/site.py:272:36: W0212: Access to a protected member _framework of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/site.py:285:4: W0603: Using the global statement (global-statement)
/log/firmware/firmware/usr/lib/python3.8/site.py:297:4: W0603: Using the global statement (global-statement)
/log/firmware/firmware/usr/lib/python3.8/site.py:338:53: E1101: Module 'sys' has no 'lib' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site.py:343:53: E1101: Module 'sys' has no 'lib' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site.py:372:25: W0212: Access to a protected member _Printer of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/site.py:374:27: W0212: Access to a protected member _Printer of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/site.py:378:27: W0212: Access to a protected member _Printer of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/site.py:388:23: W0212: Access to a protected member _Printer of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/site.py:395:20: W0212: Access to a protected member _Helper of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/site.py:407:8: C0415: Import outside toplevel (atexit) (import-outside-toplevel)
/log/firmware/firmware/usr/lib/python3.8/site.py:409:12: C0415: Import outside toplevel (readline) (import-outside-toplevel)
/log/firmware/firmware/usr/lib/python3.8/site.py:410:12: C0415: Import outside toplevel (rlcompleter) (import-outside-toplevel)
/log/firmware/firmware/usr/lib/python3.8/site.py:410:12: W0611: Unused import rlcompleter (unused-import)
/log/firmware/firmware/usr/lib/python3.8/site.py:457:4: W0603: Using the global statement (global-statement)
/log/firmware/firmware/usr/lib/python3.8/site.py:466:4: W0212: Access to a protected member _home of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/site.py:481:53: C0103: Variable name "f" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site.py:490:24: W0212: Access to a protected member _home of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/site.py:518:11: W0703: Catching too general exception Exception (broad-except)
/log/firmware/firmware/usr/lib/python3.8/site.py:512:12: C0415: Import outside toplevel (sitecustomize) (import-outside-toplevel)
/log/firmware/firmware/usr/lib/python3.8/site.py:512:12: W0611: Unused import sitecustomize (unused-import)
/log/firmware/firmware/usr/lib/python3.8/site.py:538:11: W0703: Catching too general exception Exception (broad-except)
/log/firmware/firmware/usr/lib/python3.8/site.py:532:12: C0415: Import outside toplevel (usercustomize) (import-outside-toplevel)
/log/firmware/firmware/usr/lib/python3.8/site.py:532:12: W0611: Unused import usercustomize (unused-import)
/log/firmware/firmware/usr/lib/python3.8/site.py:554:4: W0603: Using the global statement (global-statement)
/log/firmware/firmware/usr/lib/python3.8/site.py:583:4: W0622: Redefining built-in 'help' (redefined-builtin)
/log/firmware/firmware/usr/lib/python3.8/site.py:602:12: W0622: Redefining built-in 'dir' (redefined-builtin)
/log/firmware/firmware/usr/lib/python3.8/site.py:629:8: C0415: Import outside toplevel (textwrap) (import-outside-toplevel)
/log/firmware/firmware/usr/lib/python3.8/site.py:76:0: C0411: standard import "import io" should be placed before "import _sitebuiltins" (wrong-import-order)

-----------------------------------
Your code has been rated at 8.20/10

