************* Module warnings
/log/firmware/firmware/usr/lib/python3.8/warnings.py:10:0: R0913: Too many arguments (6/5) (too-many-arguments)
/log/firmware/firmware/usr/lib/python3.8/warnings.py:37:4: C0103: Variable name "s" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/warnings.py:43:15: W0703: Catching too general exception Exception (broad-except)
/log/firmware/firmware/usr/lib/python3.8/warnings.py:41:12: C0415: Import outside toplevel (linecache) (import-outside-toplevel)
/log/firmware/firmware/usr/lib/python3.8/warnings.py:52:8: C0103: Variable name "s" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/warnings.py:59:15: W0703: Catching too general exception Exception (broad-except)
/log/firmware/firmware/usr/lib/python3.8/warnings.py:56:12: C0415: Import outside toplevel (tracemalloc) (import-outside-toplevel)
/log/firmware/firmware/usr/lib/python3.8/warnings.py:62:12: C0103: Variable name "tb" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/warnings.py:67:19: W0703: Catching too general exception Exception (broad-except)
/log/firmware/firmware/usr/lib/python3.8/warnings.py:66:16: C0103: Variable name "tb" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/warnings.py:70:16: C0103: Variable name "tb" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/warnings.py:73:12: C0103: Variable name "s" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/warnings.py:75:16: C0103: Variable name "s" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/warnings.py:83:23: W0703: Catching too general exception Exception (broad-except)
/log/firmware/firmware/usr/lib/python3.8/warnings.py:87:20: C0103: Variable name "s" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/warnings.py:89:12: C0103: Variable name "s" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/warnings.py:35:0: R0912: Too many branches (15/12) (too-many-branches)
/log/firmware/firmware/usr/lib/python3.8/warnings.py:99:8: C0103: Variable name "sw" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/warnings.py:120:8: C0103: Variable name "fw" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/warnings.py:130:0: R0913: Too many arguments (6/5) (too-many-arguments)
/log/firmware/firmware/usr/lib/python3.8/warnings.py:152:8: C0415: Import outside toplevel (re) (import-outside-toplevel)
/log/firmware/firmware/usr/lib/python3.8/warnings.py:202:4: W0107: Unnecessary pass statement (unnecessary-pass)
/log/firmware/firmware/usr/lib/python3.8/warnings.py:224:8: C0415: Import outside toplevel (re) (import-outside-toplevel)
/log/firmware/firmware/usr/lib/python3.8/warnings.py:244:24: C0321: More than one statement on a single line (multiple-statements)
/log/firmware/firmware/usr/lib/python3.8/warnings.py:245:8: C0103: Variable name "a" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/warnings.py:255:8: C0415: Import outside toplevel (builtins) (import-outside-toplevel)
/log/firmware/firmware/usr/lib/python3.8/warnings.py:260:12: C0103: Variable name "m" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/warnings.py:312:8: W0622: Redefining built-in 'globals' (redefined-builtin)
/log/firmware/firmware/usr/lib/python3.8/warnings.py:300:49: W0212: Access to a protected member _getframe of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/warnings.py:303:20: W0212: Access to a protected member _getframe of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/warnings.py:305:20: W0212: Access to a protected member _getframe of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/warnings.py:307:16: C0103: Variable name "x" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/warnings.py:307:16: W0612: Unused variable 'x' (unused-variable)
/log/firmware/firmware/usr/lib/python3.8/warnings.py:327:0: R0913: Too many arguments (8/5) (too-many-arguments)
/log/firmware/firmware/usr/lib/python3.8/warnings.py:327:0: R0914: Too many local variables (19/15) (too-many-locals)
/log/firmware/firmware/usr/lib/python3.8/warnings.py:352:31: C0103: Variable name "ln" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/warnings.py:353:12: R0916: Too many boolean expressions in if statement (7/5) (too-many-boolean-expressions)
/log/firmware/firmware/usr/lib/python3.8/warnings.py:356:13: R1714: Consider merging these comparisons with "in" to 'ln in (0, lineno)' (consider-using-in)
/log/firmware/firmware/usr/lib/python3.8/warnings.py:366:4: C0415: Import outside toplevel (linecache) (import-outside-toplevel)
/log/firmware/firmware/usr/lib/python3.8/warnings.py:392:23: W0631: Using possibly undefined loop variable 'item' (undefined-loop-variable)
/log/firmware/firmware/usr/lib/python3.8/warnings.py:327:0: R0912: Too many branches (19/12) (too-many-branches)
/log/firmware/firmware/usr/lib/python3.8/warnings.py:398:0: R0205: Class 'WarningMessage' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)
/log/firmware/firmware/usr/lib/python3.8/warnings.py:398:0: R0902: Too many instance attributes (8/7) (too-many-instance-attributes)
/log/firmware/firmware/usr/lib/python3.8/warnings.py:403:4: R0913: Too many arguments (8/5) (too-many-arguments)
/log/firmware/firmware/usr/lib/python3.8/warnings.py:398:0: R0903: Too few public methods (1/2) (too-few-public-methods)
/log/firmware/firmware/usr/lib/python3.8/warnings.py:420:0: C0103: Class name "catch_warnings" doesn't conform to PascalCase naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/warnings.py:420:0: R0205: Class 'catch_warnings' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)
/log/firmware/firmware/usr/lib/python3.8/warnings.py:467:8: R1705: Unnecessary "else" after "return" (no-else-return)
/log/firmware/firmware/usr/lib/python3.8/warnings.py:462:8: W0201: Attribute '_filters' defined outside __init__ (attribute-defined-outside-init)
/log/firmware/firmware/usr/lib/python3.8/warnings.py:465:8: W0201: Attribute '_showwarning' defined outside __init__ (attribute-defined-outside-init)
/log/firmware/firmware/usr/lib/python3.8/warnings.py:466:8: W0201: Attribute '_showwarnmsg_impl' defined outside __init__ (attribute-defined-outside-init)
/log/firmware/firmware/usr/lib/python3.8/warnings.py:492:8: C0415: Import outside toplevel (linecache, traceback) (import-outside-toplevel)
/log/firmware/firmware/usr/lib/python3.8/warnings.py:492:8: C0410: Multiple imports on one line (linecache, traceback) (multiple-imports)
/log/firmware/firmware/usr/lib/python3.8/warnings.py:520:4: C0103: Constant name "defaultaction" doesn't conform to UPPER_CASE naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/warnings.py:522:4: C0103: Constant name "_warnings_defaults" doesn't conform to UPPER_CASE naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/warnings.py:525:4: C0103: Constant name "defaultaction" doesn't conform to UPPER_CASE naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/warnings.py:528:4: C0103: Constant name "_filters_version" doesn't conform to UPPER_CASE naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/warnings.py:531:8: C0103: Constant name "_filters_version" doesn't conform to UPPER_CASE naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/warnings.py:531:8: W0603: Using the global statement (global-statement)
/log/firmware/firmware/usr/lib/python3.8/warnings.py:534:4: C0103: Constant name "_warnings_defaults" doesn't conform to UPPER_CASE naming style (invalid-name)

-----------------------------------
Your code has been rated at 8.24/10

