************* Module setuptools.command.build_py
/log/firmware/firmware/usr/lib/python3.8/site-packages/setuptools/command/build_py.py:12:0: W0622: Redefining built-in 'map' (redefined-builtin)
/log/firmware/firmware/usr/lib/python3.8/site-packages/setuptools/command/build_py.py:12:0: W0622: Redefining built-in 'filter' (redefined-builtin)
/log/firmware/firmware/usr/lib/python3.8/site-packages/setuptools/command/build_py.py:11:0: E0611: No name 'six' in module 'setuptools.extern' (no-name-in-module)
/log/firmware/firmware/usr/lib/python3.8/site-packages/setuptools/command/build_py.py:12:0: E0611: No name 'six' in module 'setuptools.extern' (no-name-in-module)
/log/firmware/firmware/usr/lib/python3.8/site-packages/setuptools/command/build_py.py:18:4: R0903: Too few public methods (1/2) (too-few-public-methods)
/log/firmware/firmware/usr/lib/python3.8/site-packages/setuptools/command/build_py.py:23:0: C0103: Class name "build_py" doesn't conform to PascalCase naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/setuptools/command/build_py.py:23:0: R0901: Too many ancestors (8/7) (too-many-ancestors)
/log/firmware/firmware/usr/lib/python3.8/site-packages/setuptools/command/build_py.py:118:12: W0612: Unused variable 'package' (unused-variable)
/log/firmware/firmware/usr/lib/python3.8/site-packages/setuptools/command/build_py.py:130:30: C0103: Variable name "mf" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/setuptools/command/build_py.py:141:12: C0103: Variable name "d" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/setuptools/command/build_py.py:141:15: C0103: Variable name "f" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/setuptools/command/build_py.py:146:16: C0103: Variable name "d" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/setuptools/command/build_py.py:146:19: C0103: Variable name "df" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/setuptools/command/build_py.py:147:16: C0103: Variable name "f" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/setuptools/command/build_py.py:175:39: C0103: Variable name "f" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/setuptools/command/build_py.py:35:8: W0201: Attribute 'package_data' defined outside __init__ (attribute-defined-outside-init)
/log/firmware/firmware/usr/lib/python3.8/site-packages/setuptools/command/build_py.py:36:8: W0201: Attribute 'exclude_package_data' defined outside __init__ (attribute-defined-outside-init)
/log/firmware/firmware/usr/lib/python3.8/site-packages/setuptools/command/build_py.py:40:8: W0201: Attribute '__updated_files' defined outside __init__ (attribute-defined-outside-init)
/log/firmware/firmware/usr/lib/python3.8/site-packages/setuptools/command/build_py.py:41:8: W0201: Attribute '__doctests_2to3' defined outside __init__ (attribute-defined-outside-init)
/log/firmware/firmware/usr/lib/python3.8/site-packages/setuptools/command/build_py.py:66:12: W0201: Attribute 'data_files' defined outside __init__ (attribute-defined-outside-init)
/log/firmware/firmware/usr/lib/python3.8/site-packages/setuptools/command/build_py.py:130:8: W0201: Attribute 'manifest_files' defined outside __init__ (attribute-defined-outside-init)
/log/firmware/firmware/usr/lib/python3.8/site-packages/setuptools/command/build_py.py:260:4: C0415: Import outside toplevel (distutils.errors.DistutilsSetupError) (import-outside-toplevel)
/log/firmware/firmware/usr/lib/python3.8/site-packages/setuptools/command/build_py.py:8:0: C0412: Imports from package distutils are not grouped (ungrouped-imports)

-----------------------------------
Your code has been rated at 7.96/10

n3.8/distutils/command/build_py.py:56:8: W0201: Attribute 'data_files' defined outside __init__ (attribute-defined-outside-init)
/log/firmware/firmware/usr/lib/python3.8/distutils/command/build_py.py:394:0: C0103: Class name "build_py_2to3" doesn't conform to PascalCase naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/distutils/command/build_py.py:396:8: W0201: Attribute 'updated_files' defined outside __init__ (attribute-defined-outside-init)
/log/firmware/firmware/usr/lib/python3.8/distutils/command/build_py.py:11:0: W0614: Unused import DistutilsError from wildcard import (unused-wildcard-import)
/log/firmware/firmware/usr/lib/python3.8/distutils/command/build_py.py:11:0: W0614: Unused import DistutilsModuleError from wildcard import (unused-wildcard-import)
/log/firmware/firmware/usr/lib/python3.8/distutils/command/build_py.py:11:0: W0614: Unused import DistutilsClassError from wildcard import (unused-wildcard-import)
/log/firmware/firmware/usr/lib/python3.8/distutils/command/build_py.py:11:0: W0614: Unused import DistutilsGetoptError from wildcard import (unused-wildcard-import)
/log/firmware/firmware/usr/lib/python3.8/distutils/command/build_py.py:11:0: W0614: Unused import DistutilsArgError from wildcard import (unused-wildcard-import)
/log/firmware/firmware/usr/lib/python3.8/distutils/command/build_py.py:11:0: W0614: Unused import DistutilsSetupError from wildcard import (unused-wildcard-import)
/log/firmware/firmware/usr/lib/python3.8/distutils/command/build_py.py:11:0: W0614: Unused import DistutilsPlatformError from wildcard import (unused-wildcard-import)
/log/firmware/firmware/usr/lib/python3.8/distutils/command/build_py.py:11:0: W0614: Unused import DistutilsExecError from wildcard import (unused-wildcard-import)
/log/firmware/firmware/usr/lib/python3.8/distutils/command/build_py.py:11:0: W0614: Unused import DistutilsInternalError from wildcard import (unused-wildcard-import)
/log/firmware/firmware/usr/lib/python3.8/distutils/command/build_py.py:11:0: W0614: Unused import DistutilsTemplateError from wildcard import (unused-wildcard-import)
/log/firmware/firmware/usr/lib/python3.8/distutils/command/build_py.py:11:0: W0614: Unused import DistutilsByteCompileError from wildcard import (unused-wildcard-import)
/log/firmware/firmware/usr/lib/python3.8/distutils/command/build_py.py:11:0: W0614: Unused import CCompilerError from wildcard import (unused-wildcard-import)
/log/firmware/firmware/usr/lib/python3.8/distutils/command/build_py.py:11:0: W0614: Unused import PreprocessError from wildcard import (unused-wildcard-import)
/log/firmware/firmware/usr/lib/python3.8/distutils/command/build_py.py:11:0: W0614: Unused import CompileError from wildcard import (unused-wildcard-import)
/log/firmware/firmware/usr/lib/python3.8/distutils/command/build_py.py:11:0: W0614: Unused import LibError from wildcard import (unused-wildcard-import)
/log/firmware/firmware/usr/lib/python3.8/distutils/command/build_py.py:11:0: W0614: Unused import LinkError from wildcard import (unused-wildcard-import)
/log/firmware/firmware/usr/lib/python3.8/distutils/command/build_py.py:11:0: W0614: Unused import UnknownFileError from wildcard import (unused-wildcard-import)

-----------------------------------
Your code has been rated at 7.32/10

