************* Module gevent.tests.test__server_pywsgi
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__server_pywsgi.py:34:0: C0103: Constant name "internal_error_start" doesn't conform to UPPER_CASE naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__server_pywsgi.py:35:0: C0103: Constant name "internal_error_end" doesn't conform to UPPER_CASE naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__server_pywsgi.py:37:0: C0103: Constant name "internal_error503" doesn't conform to UPPER_CASE naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__server_pywsgi.py:83:33: W0212: Access to a protected member _NoopLog of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__server_pywsgi.py:87:0: R0901: Too many ancestors (9/7) (too-many-ancestors)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__server_pywsgi.py:90:0: R0901: Too many ancestors (10/7) (too-many-ancestors)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__server_pywsgi.py:93:0: R0901: Too many ancestors (10/7) (too-many-ancestors)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__server_pywsgi.py:99:0: R0901: Too many ancestors (10/7) (too-many-ancestors)

-----------------------------------
Your code has been rated at 8.84/10

