************* Module unittest.mock
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:1:0: C0302: Too many lines in module (2895/1000) (too-many-lines)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:46:0: C0103: Class name "_safe_super" doesn't conform to PascalCase naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:57:4: R1705: Unnecessary "else" after "return" (no-else-return)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:79:4: R1705: Unnecessary "else" after "return" (no-else-return)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:119:17: W0613: Unused argument 'self' (unused-argument)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:122:4: W0212: Access to a protected member _mock_check_sig of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:191:4: W0122: Use of exec (exec-used)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:231:4: W0212: Access to a protected member _mock_children of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:231:29: W0212: Access to a protected member _mock_children of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:243:4: W0212: Access to a protected member _mock_delegate of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:247:4: W0212: Access to a protected member _is_coroutine of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:247:25: W0212: Access to a protected member _is_coroutine of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:277:0: R0205: Class '_SentinelObject' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:289:0: R0205: Class '_Sentinel' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:322:14: W0212: Access to a protected member _mock_delegate of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:327:14: W0212: Access to a protected member _mock_delegate of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:362:9: W0212: Access to a protected member _mock_name of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:362:29: W0212: Access to a protected member _mock_new_name of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:363:9: W0212: Access to a protected member _mock_parent of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:364:9: W0212: Access to a protected member _mock_new_parent of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:373:18: W0212: Access to a protected member _mock_new_parent of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:376:8: W0212: Access to a protected member _mock_new_parent of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:377:8: W0212: Access to a protected member _mock_new_name of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:379:8: W0212: Access to a protected member _mock_parent of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:380:8: W0212: Access to a protected member _mock_name of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:384:0: R0205: Class '_MockIter' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:384:0: R0903: Too few public methods (1/2) (too-few-public-methods)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:390:0: R0205: Class 'Base' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:390:0: R0903: Too few public methods (0/2) (too-few-public-methods)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:398:0: R0902: Too many instance attributes (11/7) (too-many-instance-attributes)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:424:29: W0621: Redefining name 'wraps' from outer scope (line 37) (redefined-outer-name)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:423:4: R0913: Too many arguments (12/5) (too-many-arguments)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:475:8: W0212: Access to a protected member _mock_parent of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:476:8: W0212: Access to a protected member _mock_new_parent of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:477:8: W0212: Access to a protected member _mock_name of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:478:8: W0212: Access to a protected member _mock_new_name of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:562:8: C0103: Variable name "sf" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:565:12: C0103: Variable name "sf" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:649:12: W0621: Redefining name 'wraps' from outer scope (line 37) (redefined-outer-name)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:633:8: R1720: Unnecessary "elif" after "raise" (no-else-raise)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:646:8: R1720: Unnecessary "elif" after "raise" (no-else-raise)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:683:30: W0212: Access to a protected member _mock_new_name of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:685:15: W0212: Access to a protected member _mock_new_name of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:688:22: W0212: Access to a protected member _mock_new_parent of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:691:17: W0212: Access to a protected member _mock_name of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:738:8: R1705: Unnecessary "elif" after "return" (no-else-return)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:737:4: R1710: Either all return statements in a function should return an expression, or none of them should. (inconsistent-return-statements)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:803:58: E1133: Non-iterable value call_args is used in an iterating context (not-an-iterable)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:825:12: R1704: Redefining argument with the local name 'name' (redefined-argument-from-local)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:827:12: R1723: Unnecessary "else" after "break" (no-else-break)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:834:27: W0212: Access to a protected member _mock_children of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:835:22: W0212: Access to a protected member _spec_signature of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:861:12: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:887:11: C0113: Consider changing "not self.call_count == 1" to "self.call_count != 1" (unneeded-not)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:919:11: C0113: Consider changing "not self.call_count == 1" to "self.call_count != 1" (unneeded-not)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:593:8: W0201: Attribute 'method_calls' defined outside __init__ (attribute-defined-outside-init)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:763:12: W0201: Attribute '_spec_class' defined outside __init__ (attribute-defined-outside-init)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:1060:17: W0621: Redefining name 'wraps' from outer scope (line 37) (redefined-outer-name)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:1059:4: R0913: Too many arguments (11/5) (too-many-arguments)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:1089:8: E1101: Instance of 'CallableMixin' has no 'call_count' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:1114:34: W0212: Access to a protected member _mock_parent of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:1116:39: W0212: Access to a protected member _mock_name of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:1122:15: W0212: Access to a protected member _mock_new_name of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:1127:28: W0212: Access to a protected member _mock_new_name of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:1128:33: W0212: Access to a protected member _mock_new_name of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:1131:26: W0212: Access to a protected member _mock_new_parent of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:1139:12: R1720: Unnecessary "elif" after "raise" (no-else-raise)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:1057:0: R0903: Too few public methods (1/2) (too-few-public-methods)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:1237:0: R0205: Class '_patch' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:1237:0: R0902: Too many instance attributes (15/7) (too-many-instance-attributes)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:1242:4: R0913: Too many arguments (10/5) (too-many-arguments)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:1305:4: R0201: Method could be a function (no-self-use)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:1395:4: R0914: Too many local variables (18/15) (too-many-locals)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:1445:16: C0103: Variable name "Klass" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:1395:4: R0912: Too many branches (38/12) (too-many-branches)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:1395:4: R0915: Too many statements (91/50) (too-many-statements)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:1400:8: W0201: Attribute 'target' defined outside __init__ (attribute-defined-outside-init)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:1509:8: W0201: Attribute 'temp_original' defined outside __init__ (attribute-defined-outside-init)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:1510:8: W0201: Attribute 'is_local' defined outside __init__ (attribute-defined-outside-init)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:1572:8: W0707: Consider explicitly re-raising using the 'from' keyword (raise-missing-from)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:1578:0: R0913: Too many arguments (8/5) (too-many-arguments)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:1596:7: C0123: Using type() instead of isinstance() for a typecheck. (unidiomatic-typecheck)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:1607:0: R0913: Too many arguments (6/5) (too-many-arguments)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:1629:7: C0123: Using type() instead of isinstance() for a typecheck. (unidiomatic-typecheck)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:1656:0: R0913: Too many arguments (7/5) (too-many-arguments)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:1733:0: C0103: Class name "_patch_dict" doesn't conform to PascalCase naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:1733:0: R0205: Class '_patch_dict' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:1771:4: C0103: Argument name "f" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:1863:8: W0621: Redefining name 'patch' from outer scope (line 1656) (redefined-outer-name)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:1863:26: W0212: Access to a protected member _active_patches of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:1873:0: C0103: Constant name "magic_methods" doesn't conform to UPPER_CASE naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:1889:0: C0103: Constant name "numerics" doesn't conform to UPPER_CASE naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:1892:0: C0103: Constant name "inplace" doesn't conform to UPPER_CASE naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:1893:0: C0103: Constant name "right" doesn't conform to UPPER_CASE naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:1938:16: W0108: Lambda may not be necessary (unnecessary-lambda)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:1939:15: W0108: Lambda may not be necessary (unnecessary-lambda)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:1940:18: W0108: Lambda may not be necessary (unnecessary-lambda)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:1941:56: W0212: Access to a protected member _extract_mock_name of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:1963:18: W0212: Access to a protected member _mock_return_value of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:1973:11: W0212: Access to a protected member _mock_return_value of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:1982:18: W0212: Access to a protected member _mock_return_value of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:1992:18: W0212: Access to a protected member _mock_return_value of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:2025:0: R0903: Too few public methods (0/2) (too-few-public-methods)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:2068:0: R0903: Too few public methods (0/2) (too-few-public-methods)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:2097:4: W0231: __init__ method from base class 'Base' is not called (super-init-not-called)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:2104:8: C0103: Variable name "m" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:2104:12: W0212: Access to a protected member _get_child_mock of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:2132:29: E1101: Module 'inspect' has no 'CO_COROUTINE' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:2146:12: R1720: Unnecessary "elif" after "raise" (no-else-raise)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:2154:20: W0707: Consider explicitly re-raising using the 'from' keyword (raise-missing-from)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:2187:11: C0113: Consider changing "not self.await_count == 1" to "self.await_count != 1" (unneeded-not)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:2215:11: C0113: Consider changing "not self.await_count == 1" to "self.await_count != 1" (unneeded-not)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:2297:0: R0901: Too many ancestors (8/7) (too-many-ancestors)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:2340:0: R0205: Class '_ANY' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:2393:4: R0913: Too many arguments (6/5) (too-many-arguments)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:2393:40: W0613: Unused argument 'parent' (unused-argument)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:2394:16: W0613: Unused argument 'from_kall' (unused-argument)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:2425:4: W0231: __init__ method from base class 'tuple' is not called (super-init-not-called)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:2425:4: R0913: Too many arguments (6/5) (too-many-arguments)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:2425:23: W0613: Unused argument 'value' (unused-argument)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:2425:57: W0613: Unused argument 'two' (unused-argument)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:2432:4: R0912: Too many branches (18/12) (too-many-branches)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:2521:12: W0612: Unused variable 'name' (unused-variable)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:2561:15: W0212: Access to a protected member _mock_from_kall of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:2563:20: W0212: Access to a protected member _mock_parent of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:2570:0: R0914: Too many local variables (16/15) (too-many-locals)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:2642:8: W0212: Access to a protected member _mock_children of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:2673:12: W0212: Access to a protected member _mock_children of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:2688:12: W0212: Access to a protected member _mock_children of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:2570:0: R0912: Too many branches (25/12) (too-many-branches)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:2570:0: R0915: Too many statements (66/50) (too-many-statements)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:2716:8: R1705: Unnecessary "elif" after "return" (no-else-return)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:2729:0: R0205: Class '_SpecState' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:2731:4: R0913: Too many arguments (7/5) (too-many-arguments)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:2729:0: R0903: Too few public methods (0/2) (too-few-public-methods)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:2749:0: C0103: Constant name "file_spec" doesn't conform to UPPER_CASE naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:2753:4: R1705: Unnecessary "else" after "return" (no-else-return)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:2801:4: C0103: Constant name "file_spec" doesn't conform to UPPER_CASE naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:2801:4: W0603: Using the global statement (global-statement)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:2803:8: C0415: Import outside toplevel (_io) (import-outside-toplevel)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:2824:0: W0613: Unused argument 'args' (unused-argument)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:2824:0: W0613: Unused argument 'kwargs' (unused-argument)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:2865:4: W0212: Access to a protected member _mock_sealed of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:2868:12: C0103: Variable name "m" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:2873:11: W0212: Access to a protected member _mock_new_parent of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/unittest/mock.py:2884:29: E1101: Module 'inspect' has no 'CO_ITERABLE_COROUTINE' member (no-member)

-----------------------------------
Your code has been rated at 8.95/10

