************* Module werkzeug.routing
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:1:0: C0302: Too many lines in module (2341/1000) (too-many-lines)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:113:0: W0404: Reimport 'typing' (imported line 112) (reimported)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:226:8: C0103: Variable name "m" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:328:23: W0212: Access to a protected member _rules of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:329:23: W0212: Access to a protected member _rules of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:381:24: W0622: Redefining built-in 'map' (redefined-builtin)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:375:0: R0903: Too few public methods (1/2) (too-few-public-methods)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:410:24: W0622: Redefining built-in 'map' (redefined-builtin)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:387:0: R0903: Too few public methods (1/2) (too-few-public-methods)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:436:24: W0622: Redefining built-in 'map' (redefined-builtin)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:418:0: R0903: Too few public methods (1/2) (too-few-public-methods)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:461:24: W0622: Redefining built-in 'map' (redefined-builtin)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:444:0: R0903: Too few public methods (1/2) (too-few-public-methods)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:469:0: R0903: Too few public methods (1/2) (too-few-public-methods)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:508:24: W0622: Redefining built-in 'map' (redefined-builtin)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:495:0: R0903: Too few public methods (1/2) (too-few-public-methods)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:557:0: R0902: Too many instance attributes (22/7) (too-many-instance-attributes)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:681:4: R0913: Too many arguments (13/5) (too-many-arguments)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:773:24: W0622: Redefining built-in 'map' (redefined-builtin)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:784:19: W0622: Redefining built-in 'map' (redefined-builtin)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:803:8: W0613: Unused argument 'variable_name' (unused-argument)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:824:4: R0915: Too many statements (57/50) (too-many-statements)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:913:12: C0103: Variable name "m" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:921:20: R0916: Too many boolean expressions in if statement (6/5) (too-many-boolean-expressions)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:971:8: W0122: Use of exec (exec-used)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:974:4: R0914: Too many local variables (22/15) (too-many-locals)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:1012:16: C0103: Variable name "p" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:1062:27: W0212: Access to a protected member _attributes of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:1064:31: W0212: Access to a protected member _attributes of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:1079:12: R1705: Unnecessary "else" after "return" (no-else-return)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:834:8: W0201: Attribute '_converters' defined outside __init__ (attribute-defined-outside-init)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:835:8: W0201: Attribute '_static_weights' defined outside __init__ (attribute-defined-outside-init)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:836:8: W0201: Attribute '_argument_weights' defined outside __init__ (attribute-defined-outside-init)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:878:8: W0201: Attribute '_build' defined outside __init__ (attribute-defined-outside-init)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:879:8: W0201: Attribute '_build' defined outside __init__ (attribute-defined-outside-init)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:880:8: W0201: Attribute '_build_unknown' defined outside __init__ (attribute-defined-outside-init)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:881:8: W0201: Attribute '_build_unknown' defined outside __init__ (attribute-defined-outside-init)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:895:8: W0201: Attribute '_regex' defined outside __init__ (attribute-defined-outside-init)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:1195:23: W0622: Redefining built-in 'map' (redefined-builtin)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:1195:0: W0613: Unused argument 'args' (unused-argument)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:1195:0: W0613: Unused argument 'kwargs' (unused-argument)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:1198:4: R0201: Method could be a function (no-self-use)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:1227:8: W0622: Redefining built-in 'map' (redefined-builtin)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:1255:23: W0622: Redefining built-in 'map' (redefined-builtin)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:1285:8: W0622: Redefining built-in 'map' (redefined-builtin)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:1287:8: W0622: Redefining built-in 'min' (redefined-builtin)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:1288:8: W0622: Redefining built-in 'max' (redefined-builtin)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:1283:4: R0913: Too many arguments (6/5) (too-many-arguments)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:1369:8: W0622: Redefining built-in 'map' (redefined-builtin)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:1370:8: W0622: Redefining built-in 'min' (redefined-builtin)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:1371:8: W0622: Redefining built-in 'max' (redefined-builtin)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:1411:0: R0902: Too many instance attributes (14/7) (too-many-instance-attributes)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:1464:4: R0913: Too many arguments (12/5) (too-many-arguments)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:1481:27: E1121: Too many positional arguments for function call (too-many-function-args)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:1545:4: R0913: Too many arguments (8/5) (too-many-arguments)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:1597:8: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:1741:0: R0902: Too many instance attributes (9/7) (too-many-instance-attributes)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:1749:8: W0622: Redefining built-in 'map' (redefined-builtin)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:1747:4: R0913: Too many arguments (9/5) (too-many-arguments)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:1822:16: E0633: Attempting to unpack a non-sequence (unpacking-non-sequence)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:1823:12: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:1826:8: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:1832:4: R0913: Too many arguments (6/5) (too-many-arguments)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:1843:4: R0913: Too many arguments (6/5) (too-many-arguments)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:1853:4: R0913: Too many arguments (6/5) (too-many-arguments)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:1853:4: R0914: Too many local variables (18/15) (too-many-locals)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:1969:20: W0212: Access to a protected member _rules of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:1971:16: C0103: Variable name "rv" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:1972:12: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:1979:12: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:2004:32: W0640: Cell variable rv defined in loop (cell-var-from-loop)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:2005:31: W0212: Access to a protected member _converters of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:2005:31: W0640: Cell variable rule defined in loop (cell-var-from-loop)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:2030:12: R1705: Unnecessary "else" after "return" (no-else-return)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:1853:4: R0912: Too many branches (22/12) (too-many-branches)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:1853:4: R0915: Too many statements (56/50) (too-many-statements)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:2069:8: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:2090:8: R1705: Unnecessary "else" after "return" (no-else-return)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:2108:12: C0103: Variable name "r" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:2108:17: W0212: Access to a protected member _rules_by_endpoint of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:2145:4: R0913: Too many arguments (6/5) (too-many-arguments)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:2176:12: C0103: Variable name "rv" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:2187:20: W0212: Access to a protected member _rules_by_endpoint of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:2192:20: C0103: Variable name "rv" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:2194:24: R1705: Unnecessary "elif" after "return" (no-else-return)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:2203:4: R0913: Too many arguments (7/5) (too-many-arguments)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:2203:4: R0914: Too many local variables (18/15) (too-many-locals)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:2312:8: C0103: Variable name "rv" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:143:4: W0611: Unused typing_extensions imported as te (unused-import)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:144:4: W0611: Unused WSGIApplication imported from _typeshed.wsgi (unused-import)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:145:4: W0611: Unused WSGIEnvironment imported from _typeshed.wsgi (unused-import)
/log/firmware/firmware/usr/lib/python3.8/site-packages/werkzeug/routing.py:146:4: W0611: Unused Response imported from wrappers.response (unused-import)

-----------------------------------
Your code has been rated at 8.79/10

