************* Module gevent.tests.test__socket_dns
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:32:0: C0413: Import "from gevent.testing.sysinfo import RESOLVER_NOT_SYSTEM" should be placed at the top of the module (wrong-import-position)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:33:0: C0413: Import "from gevent.testing.sysinfo import RESOLVER_DNSPYTHON" should be placed at the top of the module (wrong-import-position)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:34:0: C0413: Import "from gevent.testing.sysinfo import RESOLVER_ARES" should be placed at the top of the module (wrong-import-position)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:35:0: C0413: Import "from gevent.testing.sysinfo import PY2" should be placed at the top of the module (wrong-import-position)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:36:0: C0413: Import "from gevent.testing.sysinfo import PYPY" should be placed at the top of the module (wrong-import-position)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:37:0: C0413: Import "import gevent.testing.timing" should be placed at the top of the module (wrong-import-position)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:40:7: E1101: Module 'gevent.socket' has no 'gaierror' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:52:4: C0103: Argument name "n" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:66:8: C0103: Variable name "x" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:67:8: W0212: Access to a protected member _test of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:72:8: C0103: Variable name "x" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:73:17: W0212: Access to a protected member _test of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:75:12: W0212: Access to a protected member _test of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:80:8: C0103: Variable name "x" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:81:8: W0212: Access to a protected member _test of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:86:8: C0103: Variable name "x" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:87:8: W0212: Access to a protected member _test of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:92:8: C0103: Variable name "x" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:93:8: W0212: Access to a protected member _test of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:98:0: R0901: Too many ancestors (8/7) (too-many-ancestors)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:130:4: R0201: Method could be a function (no-self-use)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:141:4: R0201: Method could be a function (no-self-use)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:168:8: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:180:8: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:234:8: R0201: Method could be a function (no-self-use)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:236:8: R0201: Method could be a function (no-self-use)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:239:8: R0201: Method could be a function (no-self-use)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:301:4: R0201: Method could be a function (no-self-use)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:390:4: C0103: Argument name "a" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:390:4: C0103: Argument name "b" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:390:4: R0201: Method could be a function (no-self-use)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:408:4: R0201: Method could be a function (no-self-use)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:414:4: C0103: Method name "assertEqualResults" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:461:0: R0901: Too many ancestors (9/7) (too-many-ancestors)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:468:0: R0901: Too many ancestors (9/7) (too-many-ancestors)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:471:4: R0201: Method could be a function (no-self-use)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:502:0: R0901: Too many ancestors (9/7) (too-many-ancestors)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:514:15: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:522:21: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:542:0: R0901: Too many ancestors (9/7) (too-many-ancestors)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:548:0: R0901: Too many ancestors (9/7) (too-many-ancestors)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:554:0: R0901: Too many ancestors (9/7) (too-many-ancestors)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:566:0: R0901: Too many ancestors (9/7) (too-many-ancestors)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:574:8: R0201: Method could be a function (no-self-use)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:582:0: C0413: Import "from gevent.resolver._hostsfile import HostsFile" should be placed at the top of the module (wrong-import-position)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:585:26: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:608:0: R0901: Too many ancestors (9/7) (too-many-ancestors)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:614:8: C0103: Variable name "hf" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:620:18: C0103: Variable name "ip" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:677:8: C0103: Attribute name "NORMALIZE_GAI_IGNORE_CANONICAL_NAME" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:630:0: R0901: Too many ancestors (9/7) (too-many-ancestors)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:643:8: R0201: Method could be a function (no-self-use)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:649:21: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:654:4: C0103: Method name "test_AI_CANONNAME" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:673:24: E1101: Module 'gevent.socket' has no 'getaddrinfo' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:686:0: R0901: Too many ancestors (9/7) (too-many-ancestors)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:703:0: C0103: Class name "Test_getaddrinfo" doesn't conform to PascalCase naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:703:0: R0901: Too many ancestors (9/7) (too-many-ancestors)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:745:14: E1101: Module 'gevent.socket' has no 'getaddrinfo' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:748:8: C0103: Variable name "af" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:752:0: R0901: Too many ancestors (9/7) (too-many-ancestors)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:778:0: C0103: Class name "TestInterrupted_gethostbyname" doesn't conform to PascalCase naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:778:0: R0901: Too many ancestors (10/7) (too-many-ancestors)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:784:8: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:790:20: E1101: Module 'gevent.socket' has no 'gethostbyname' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:795:4: R0201: Method could be a function (no-self-use)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:832:0: R0901: Too many ancestors (9/7) (too-many-ancestors)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:837:0: R0901: Too many ancestors (9/7) (too-many-ancestors)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:844:0: C0103: Class name "Test_getnameinfo_127001" doesn't conform to PascalCase naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:844:0: R0901: Too many ancestors (9/7) (too-many-ancestors)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:849:4: C0103: Method name "test_DGRAM" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:853:4: C0103: Method name "test_NOFQDN" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:857:4: C0103: Method name "test_NAMEREQD" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:861:0: C0103: Class name "Test_getnameinfo_geventorg" doesn't conform to PascalCase naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:861:0: R0901: Too many ancestors (9/7) (too-many-ancestors)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:865:4: C0103: Method name "test_NUMERICHOST" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:871:4: C0103: Method name "test_NUMERICSERV" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:884:0: C0103: Class name "Test_getnameinfo_fail" doesn't conform to PascalCase naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:884:0: R0901: Too many ancestors (9/7) (too-many-ancestors)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:893:0: R0901: Too many ancestors (9/7) (too-many-ancestors)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:9:0: C0411: standard import "import os" should be placed before "import gevent" (wrong-import-order)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:10:0: C0411: standard import "import re" should be placed before "import gevent" (wrong-import-order)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:12:0: C0411: standard import "import unittest" should be placed before "import gevent" (wrong-import-order)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:13:0: C0411: standard import "import socket" should be placed before "import gevent" (wrong-import-order)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:14:0: C0411: standard import "from time import time" should be placed before "import gevent" (wrong-import-order)
/log/firmware/firmware/usr/lib/python3.8/site-packages/gevent/tests/test__socket_dns.py:15:0: C0411: standard import "import traceback" should be placed before "import gevent" (wrong-import-order)

-----------------------------------
Your code has been rated at 7.83/10

